{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.7.1-K2.3.0-SNAPSHOT/testBalloon-framework-core-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-shared",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-linuxArm64Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-linuxarm64-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 136311,
          "sha512": "c2d63775a27bf0a9dd3204e2d78f6e22e31d2a2ba64e1fe5dd84178e700624b6b97954ea5cd7c38ae9617c4f31a88d44d0d872cca81cb3618f779e7d55973e89",
          "sha256": "05ec922a2bd3c1b21000b829957d3d65b49cbc34f94c25d5ee0d5241e05393c1",
          "sha1": "6b9a52429c6edd9f9f2a4ef6193100df472edf18",
          "md5": "0bb546eb6877145bf6d65a97718687fa"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-linuxarm64-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-linuxarm64-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 36702,
          "sha512": "39150b68f51c8537bedb5da6974b9a30b8cbba233aa3edf14f96d72649a7fde1ffd6a8a43e0d158eae7b2b828c9bda73f008d61fda4abe149bb273e94b9c85c0",
          "sha256": "b820b1b0353db9510284af2e32ff926e543fd2d83f993a9a5b0afc7b59dd1a62",
          "sha1": "50b2fa826d95d072a8b02084e452db36d6cd1d34",
          "md5": "bfecdd1483ab04c4987204a1e136b4e5"
        }
      ]
    }
  ]
}
