{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-macosX64Main-3.20.0-PREVIEW.klib",
          "url": "internals-macosx64-3.20.0-PREVIEW.klib",
          "size": 12881,
          "sha512": "05b40da534c5259505d8ae6cce7fe5ccbd651b4228c81650133492f95d3f195109f0e0a32b0a3a1b9c89083db66a9d0d231942465af372f91875c434cc2e08bf",
          "sha256": "4d1e7eb4da7d6fddbdef936af836eb9e6996d91cefe73ed8c7dca37a77acb1b2",
          "sha1": "31e8d29c2a2aee427a1e79c00a65ff2de0f3f2a0",
          "md5": "af7070cb2b156981a88c725ebe6b7cdc"
        }
      ]
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "internals-macosx64-3.20.0-PREVIEW-sources.jar",
          "url": "internals-macosx64-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-macosx64-3.20.0-PREVIEW-metadata.jar",
          "url": "internals-macosx64-3.20.0-PREVIEW-metadata.jar",
          "size": 3911,
          "sha512": "1ee6395381e3a560424055864bc433ceb883e0deabff6fcdcec9b01957344cc8e818a6a1be73fcbfdb3d91f0e38b5667b20db9a391742636e121cf5107dab52a",
          "sha256": "e65a252f779a004d9643b0c89e5f4cf6712fd386c236f5041fc674ba409a9d59",
          "sha1": "11f59658e6c68b50a204cebb5c77726fee45deae",
          "md5": "1cf423e1c70d5e3f80cc9d585fbf4b0d"
        }
      ]
    }
  ]
}
