{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-kotest-assertions/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-kotest-assertions-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-kotest-assertions",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-androidNativeX86Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-kotest-assertions-androidnativex86-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 4288,
          "sha512": "4069e143827e87f91c4d96814ec302a6d1894390b31447f71a0a2dd7cdb7158e8945ae9626bcf910153ff83cd6eba2b775a384bf23f0e620432308f96449ac12",
          "sha256": "4f030932dee403dfc93b94622d8ee514b9c56202f98472abefad55702f9348ec",
          "sha1": "3f955ea93c2e85ab97a86e7cab0791072f173da0",
          "md5": "40b344e0c58fc66da06ad0c852f215ce"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-androidnativex86-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-kotest-assertions-androidnativex86-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 3236,
          "sha512": "898f83a47747cd16f731ae234f7a75243e685d83b3c7732e51b11c1d92dfce285cbaadebcc78adb905a42d2e957c8ac0eb318225e9b7976b216240c895f0032a",
          "sha256": "a888e91399b9e5c57414f5f168fd4fe3e7417eb6a04ccdc1e3183e5d81a57861",
          "sha1": "7db47688e4008a34325218c3ef8aead1631ca286",
          "md5": "d795842e946080d386afd4a6ddb73bf7"
        }
      ]
    }
  ]
}
