{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.12.0-PREVIEW/supreme-0.12.0-PREVIEW.module",
    "group": "Signum",
    "module": "supreme",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosX64Main-0.12.0-PREVIEW.klib",
          "url": "supreme-iosx64-0.12.0-PREVIEW.klib",
          "size": 461770,
          "sha512": "132c6904f9ca51ee17175c85497a80595ab6b96cced855bcdfb2fe17f8bd076ac75589e4424489c27e733e555ddda9093fd81031a46e38efb72090d41c0fedbf",
          "sha256": "93b1184da8dbd02b2968bb28ca91c6a1afdfb03fdea477996b75b9ffbc7bca06",
          "sha1": "85a4a871e11566e2170f9f5bd40391a12c7f324b",
          "md5": "314b9042ae7a2a508fd55539d3d66342"
        },
        {
          "name": "supreme-iosX64Cinterop-cinteropMain-0.12.0-PREVIEW.klib",
          "url": "supreme-iosx64-0.12.0-PREVIEW-cinterop-cinterop.klib",
          "size": 42897,
          "sha512": "1a0042df157f53e190665e4e57c5762c3be0a399d4b0fc268ec58d6f1d74d7b00ec8220f6a279967d92644edd332a1527893f2e85050f531253b1365ebe993b1",
          "sha256": "3289c7cb9318b2fe6f2ebf91a66f1aae67ae8322117b74b3b28af313360eb7f5",
          "sha1": "90b27b1df41a7a0a3a48c8ae237ec2ae63fdeac5",
          "md5": "f6ea69c4ad84c669bf51060c60f59f0d"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "supreme-iosx64-0.12.0-PREVIEW-sources.jar",
          "url": "supreme-iosx64-0.12.0-PREVIEW-sources.jar",
          "size": 206085,
          "sha512": "5ae6511bc4c540da998d6a01299735243042bf3f41651ee67d53781bd297129cd9df0dcd21fd92676b103481e50bfcb9a3b83311c5b63c7dd83acf3b53b25ebe",
          "sha256": "7fabf8f94a273e08a955cf6cb0110b98e62b31a4035133fc3d20353bec7550df",
          "sha1": "7c499854b312d6f9376c3a0ffcaf0620998c59d3",
          "md5": "e62eb50eda845b4cb8821fd02230ce97"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosx64-0.12.0-PREVIEW-metadata.jar",
          "url": "supreme-iosx64-0.12.0-PREVIEW-metadata.jar",
          "size": 41320,
          "sha512": "4013ccfb8013c75091f801b961717bcb436bc994fb413c8607a11c6e1563475b50f5e0809beff51d5e649e366261cea35650cf34b7f5c7a2ac030747571a9030",
          "sha256": "e1413b2133ec176ada0e7419de5b46de74bbb88f01214627b4a45cb03bcefa06",
          "sha1": "f008fb22e08b230e2c9fc5389a7e9d19490fe4d3",
          "md5": "1536970c73c3ad500189fb23fa8c1144"
        }
      ]
    }
  ]
}
