{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-asn1-versionCatalog",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "indispensable-asn1-versionCatalog-3.20.0-PREVIEW.toml",
          "url": "indispensable-asn1-versionCatalog-3.20.0-PREVIEW.toml",
          "size": 2196,
          "sha512": "0c87e0c55ef5a49428eaaa883dc17bf340b0c442d98b870ec6392a259addd03660e6260ba4cc5949464d9e9cb85f5b6509cb0faaf96ff13fd288f045df90c8bb",
          "sha256": "e4ebc41518d83a6cc7fe06228c90572e82f9746605f908354a85eeee09bcb70d",
          "sha1": "b44cfe2d126570b1b32073656bf1760868362d99",
          "md5": "fc2a1bd9b0c123361b381a5a33b032db"
        }
      ]
    }
  ]
}
