{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-oids/3.20.0-PREVIEW/indispensable-oids-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable-oids",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "size": 579393,
          "sha512": "fe88066a3b7f748d7338b596f095530b26ddc4fe307a919c0009c1867c40c92d9b298002cfc8af405f81954e36c4e23c40326765aaf251fdbf4ac66526c9544c",
          "sha256": "265ea5da9bd0367b91a949f1614f60ee572b01fc1c6f934918b35d09840b089e",
          "sha1": "23441af79b8657e8428633ae6d4d11f2a34e6be2",
          "md5": "5c6276ba0ea047161fd43cbfd7f0c778"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "size": 579393,
          "sha512": "fe88066a3b7f748d7338b596f095530b26ddc4fe307a919c0009c1867c40c92d9b298002cfc8af405f81954e36c4e23c40326765aaf251fdbf4ac66526c9544c",
          "sha256": "265ea5da9bd0367b91a949f1614f60ee572b01fc1c6f934918b35d09840b089e",
          "sha1": "23441af79b8657e8428633ae6d4d11f2a34e6be2",
          "md5": "5c6276ba0ea047161fd43cbfd7f0c778"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "indispensable-oids-wasm-js-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-oids-wasm-js-3.20.0-PREVIEW-sources.jar",
          "size": 87050,
          "sha512": "fc6f1cec4fa7ebc507924ead1b0a626eae184148380f6f0c64f60d234ba1b6532dfb78900478706797fb1cc26205d896dd7d3b290feca56abac0ae5873499ca7",
          "sha256": "e8a4c0b7953f5cb49349bdd5b7cbb26701353f992af01785aba7385d4fc42040",
          "sha1": "b630e3a0a9844af8d0c177f04cbe0519e1fa5039",
          "md5": "c61df4e0a0eff6ba6613137add0bbfb8"
        }
      ]
    }
  ]
}
