{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-oids/3.20.0-PREVIEW/indispensable-oids-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable-oids",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "size": 579394,
          "sha512": "2b79186af8599ffe4d1fc1b1c1105e78cbfc96967f3b34996ddf9e24d47f46e279231948572ca0e194f648498b790c9dd7d64e5cc97deb9f8592160fa5f3e2a8",
          "sha256": "fa5feccf9cc16287b500e1e097ccbde242262cbfd30e8e4df819e780cc01c7ec",
          "sha1": "ac822155843396527895e5790ad755683c448754",
          "md5": "16bdfd65cf70c203d1a8d8605699d896"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-oids-wasm-js-3.20.0-PREVIEW.klib",
          "size": 579394,
          "sha512": "2b79186af8599ffe4d1fc1b1c1105e78cbfc96967f3b34996ddf9e24d47f46e279231948572ca0e194f648498b790c9dd7d64e5cc97deb9f8592160fa5f3e2a8",
          "sha256": "fa5feccf9cc16287b500e1e097ccbde242262cbfd30e8e4df819e780cc01c7ec",
          "sha1": "ac822155843396527895e5790ad755683c448754",
          "md5": "16bdfd65cf70c203d1a8d8605699d896"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "indispensable-oids-wasm-js-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-oids-wasm-js-3.20.0-PREVIEW-sources.jar",
          "size": 87050,
          "sha512": "fc6f1cec4fa7ebc507924ead1b0a626eae184148380f6f0c64f60d234ba1b6532dfb78900478706797fb1cc26205d896dd7d3b290feca56abac0ae5873499ca7",
          "sha256": "e8a4c0b7953f5cb49349bdd5b7cbb26701353f992af01785aba7385d4fc42040",
          "sha1": "b630e3a0a9844af8d0c177f04cbe0519e1fa5039",
          "md5": "c61df4e0a0eff6ba6613137add0bbfb8"
        }
      ]
    }
  ]
}
