{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-kotest-assertions/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-kotest-assertions-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-kotest-assertions",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-kotest-assertions-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 4088,
          "sha512": "67c49b87707f5d5282ce5ee3def97d55edb4bc4361ad9b379c4dc08248658975d3c8db1a344d1fa054ecf21fc8f2a805c4213377898f459260a5de4eb5513a24",
          "sha256": "adef5cbaee23dc90813e39b7db26f09a779aa6619a31d239b9bd9226b1a5f350",
          "sha1": "649bd4cacb76e538df5f5ed81e2cfbc41aa04d37",
          "md5": "3b5d116198a6a3eee5cfd4561b1bc26b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-kotest-assertions-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 4088,
          "sha512": "67c49b87707f5d5282ce5ee3def97d55edb4bc4361ad9b379c4dc08248658975d3c8db1a344d1fa054ecf21fc8f2a805c4213377898f459260a5de4eb5513a24",
          "sha256": "adef5cbaee23dc90813e39b7db26f09a779aa6619a31d239b9bd9226b1a5f350",
          "sha1": "649bd4cacb76e538df5f5ed81e2cfbc41aa04d37",
          "md5": "3b5d116198a6a3eee5cfd4561b1bc26b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-wasm-js-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-kotest-assertions-wasm-js-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 3236,
          "sha512": "898f83a47747cd16f731ae234f7a75243e685d83b3c7732e51b11c1d92dfce285cbaadebcc78adb905a42d2e957c8ac0eb318225e9b7976b216240c895f0032a",
          "sha256": "a888e91399b9e5c57414f5f168fd4fe3e7417eb6a04ccdc1e3183e5d81a57861",
          "sha1": "7db47688e4008a34325218c3ef8aead1631ca286",
          "md5": "d795842e946080d386afd4a6ddb73bf7"
        }
      ]
    }
  ]
}
