{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-cosef",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-cosef-metadata-3.20.0-PREVIEW.jar",
          "url": "indispensable-cosef-3.20.0-PREVIEW.jar",
          "size": 21420,
          "sha512": "c479e440e1aa4c65b1e44ff9f7152386ae837e042f0c7a0fba7cc65b67b3eba0f229c11f0ca3c99a1ea679bb990609cf080718d6014c5e4c5dbd0007ecdecc08",
          "sha256": "12b0a0c95931af1572d96c4bdbada10d3c56fb9c20d6e7e48e913308184c1234",
          "sha1": "b96da3089d3d378603ff65ed1e384f2a63273e0f",
          "md5": "eef20e5b79f294a2906a6d6dba8308f2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "indispensable-cosef-kotlin-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-cosef-3.20.0-PREVIEW-sources.jar",
          "size": 28704,
          "sha512": "22ffd64377ce9ed685a107a46cb783fa414eafa12e042967a490ac2839ffc9bf33ba8f6e6856a5fcad88b8e8da772722955b2e36e679117b10e08b63252aea24",
          "sha256": "8d707a316871d4a28cd60b1416369b60e2418d82c6383e6fe003dab458d48fcb",
          "sha1": "a719004b082df10f49e36f64553beba740d6bfc3",
          "md5": "5e02234840ffa904888f62ac3b9af9d5"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-cosef-android/3.20.0-PREVIEW/indispensable-cosef-android-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-android",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-cosef-android/3.20.0-PREVIEW/indispensable-cosef-android-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-android",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-cosef-android/3.20.0-PREVIEW/indispensable-cosef-android-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-android",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativearm32/3.20.0-PREVIEW/indispensable-cosef-androidnativearm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativearm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativearm32/3.20.0-PREVIEW/indispensable-cosef-androidnativearm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativearm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativearm64/3.20.0-PREVIEW/indispensable-cosef-androidnativearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativearm64/3.20.0-PREVIEW/indispensable-cosef-androidnativearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativex64/3.20.0-PREVIEW/indispensable-cosef-androidnativex64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativex64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativex64/3.20.0-PREVIEW/indispensable-cosef-androidnativex64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativex64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativex86/3.20.0-PREVIEW/indispensable-cosef-androidnativex86-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativex86",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-androidnativex86/3.20.0-PREVIEW/indispensable-cosef-androidnativex86-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-androidnativex86",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iosarm64/3.20.0-PREVIEW/indispensable-cosef-iosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iosarm64/3.20.0-PREVIEW/indispensable-cosef-iosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iosarm64/3.20.0-PREVIEW/indispensable-cosef-iosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-iossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-iossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-iossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iosx64/3.20.0-PREVIEW/indispensable-cosef-iosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iosx64/3.20.0-PREVIEW/indispensable-cosef-iosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-iosx64/3.20.0-PREVIEW/indispensable-cosef-iosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-iosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../indispensable-cosef-js/3.20.0-PREVIEW/indispensable-cosef-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../indispensable-cosef-js/3.20.0-PREVIEW/indispensable-cosef-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../indispensable-cosef-js/3.20.0-PREVIEW/indispensable-cosef-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-cosef-jvm/3.20.0-PREVIEW/indispensable-cosef-jvm-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-jvm",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-cosef-jvm/3.20.0-PREVIEW/indispensable-cosef-jvm-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-jvm",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-cosef-jvm/3.20.0-PREVIEW/indispensable-cosef-jvm-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-jvm",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-linuxarm64/3.20.0-PREVIEW/indispensable-cosef-linuxarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-linuxarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-linuxarm64/3.20.0-PREVIEW/indispensable-cosef-linuxarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-linuxarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-linuxx64/3.20.0-PREVIEW/indispensable-cosef-linuxx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-linuxx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-linuxx64/3.20.0-PREVIEW/indispensable-cosef-linuxx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-linuxx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-macosarm64/3.20.0-PREVIEW/indispensable-cosef-macosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-macosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-macosarm64/3.20.0-PREVIEW/indispensable-cosef-macosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-macosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-macosarm64/3.20.0-PREVIEW/indispensable-cosef-macosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-macosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-macosx64/3.20.0-PREVIEW/indispensable-cosef-macosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-macosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-macosx64/3.20.0-PREVIEW/indispensable-cosef-macosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-macosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-macosx64/3.20.0-PREVIEW/indispensable-cosef-macosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-macosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-mingwx64/3.20.0-PREVIEW/indispensable-cosef-mingwx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-mingwx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-mingwx64/3.20.0-PREVIEW/indispensable-cosef-mingwx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-mingwx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvosarm64/3.20.0-PREVIEW/indispensable-cosef-tvosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvosarm64/3.20.0-PREVIEW/indispensable-cosef-tvosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvosarm64/3.20.0-PREVIEW/indispensable-cosef-tvosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-tvossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-tvossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-tvossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvosx64/3.20.0-PREVIEW/indispensable-cosef-tvosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvosx64/3.20.0-PREVIEW/indispensable-cosef-tvosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-tvosx64/3.20.0-PREVIEW/indispensable-cosef-tvosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-tvosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../indispensable-cosef-wasm-js/3.20.0-PREVIEW/indispensable-cosef-wasm-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-wasm-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../indispensable-cosef-wasm-js/3.20.0-PREVIEW/indispensable-cosef-wasm-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-wasm-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../indispensable-cosef-wasm-js/3.20.0-PREVIEW/indispensable-cosef-wasm-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-wasm-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosarm32/3.20.0-PREVIEW/indispensable-cosef-watchosarm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosarm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosarm32/3.20.0-PREVIEW/indispensable-cosef-watchosarm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosarm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosarm32/3.20.0-PREVIEW/indispensable-cosef-watchosarm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosarm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosarm64/3.20.0-PREVIEW/indispensable-cosef-watchosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosarm64/3.20.0-PREVIEW/indispensable-cosef-watchosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosarm64/3.20.0-PREVIEW/indispensable-cosef-watchosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-watchossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-watchossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchossimulatorarm64/3.20.0-PREVIEW/indispensable-cosef-watchossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosx64/3.20.0-PREVIEW/indispensable-cosef-watchosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosx64/3.20.0-PREVIEW/indispensable-cosef-watchosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-cosef-watchosx64/3.20.0-PREVIEW/indispensable-cosef-watchosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-cosef-watchosx64",
        "version": "3.20.0-PREVIEW"
      }
    }
  ]
}
