{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-josef-versionCatalog",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "indispensable-josef-versionCatalog-3.20.0-PREVIEW.toml",
          "url": "indispensable-josef-versionCatalog-3.20.0-PREVIEW.toml",
          "size": 2387,
          "sha512": "a71f9304ebe1539b83a5ac5e94861c65fc415c4250d67b00be5a479ba0fb84a7654e40cc65dbb1ba3bf04bc50d17500ebc4df1a43e8488f259172850fc478b7f",
          "sha256": "d1f65354019ab8a2f88bac8d8d6158a6fb735d12a46631fadd94131b078f0079",
          "sha1": "d947ac6c55f6361c2f4fcc01605cc773722cf284",
          "md5": "4691603bdc7ae9850079f22b9eec4724"
        }
      ]
    }
  ]
}
