package at.asitplus.signum.supreme.sign

import at.asitplus.KmmResult
import at.asitplus.catching
import at.asitplus.signum.indispensable.CryptoPublicKey
import at.asitplus.signum.indispensable.CryptoSignature
import at.asitplus.signum.indispensable.Digest
import at.asitplus.signum.indispensable.ECCurve
import at.asitplus.signum.indispensable.RSAPadding
import at.asitplus.signum.indispensable.SignatureAlgorithm
import at.asitplus.signum.indispensable.nativeDigest
import at.asitplus.signum.supreme.HazardousMaterials
import at.asitplus.signum.supreme.UnlockFailed
import at.asitplus.signum.supreme.dsl.DSL
import at.asitplus.signum.supreme.dsl.DSLConfigureFn
import at.asitplus.signum.supreme.os.Attestation
import com.ionspin.kotlin.bignum.integer.BigInteger

open class SigningKeyConfiguration internal constructor(): DSL.Data() {
    sealed class AlgorithmSpecific: DSL.Data()
    internal val _algSpecific = subclassOf<AlgorithmSpecific>(default = ECConfiguration())
    open class ECConfiguration internal constructor() : AlgorithmSpecific() {
        var curve: ECCurve = ECCurve.SECP_256_R_1

        private var _digests: Set<Digest?>? = null
        /** Specify the digests supported by the key. If not specified, supports the curve's native digest only. */
        open var digests: Set<Digest?>
            get() = _digests ?: setOf(curve.nativeDigest)
            set(v) { _digests = v }
    }
    open val ec = _algSpecific.option(::ECConfiguration)

    open class RSAConfiguration internal constructor(): AlgorithmSpecific() {
        companion object { val F0 = BigInteger(3); val F4 = BigInteger(65537) }
        open var digests: Set<Digest> = setOf(Digest.SHA256)
        open var paddings: Set<RSAPadding> = setOf(RSAPadding.PSS)
        var bits: Int = 4096
        var publicExponent: BigInteger = F4
    }
    open val rsa = _algSpecific.option(::RSAConfiguration)
}

interface Signer {
    val signatureAlgorithm: SignatureAlgorithm
    val publicKey: CryptoPublicKey
    /** Whether the signer may ask for user interaction when [sign] is called */
    val mayRequireUserUnlock: Boolean

    /** Any [Signer] instantiation must be [ECDSA] or [RSA] */
    sealed interface AlgTrait : Signer

    /** ECDSA signer */
    interface ECDSA : Signer.AlgTrait {
        override val signatureAlgorithm: SignatureAlgorithm.ECDSA
        override val publicKey: CryptoPublicKey.EC
    }

    /** RSA signer */
    interface RSA : Signer.AlgTrait {
        override val signatureAlgorithm: SignatureAlgorithm.RSA
        override val publicKey: CryptoPublicKey.Rsa
    }

    /** Some [Signer]s are retrieved from a signing provider, such as a key store, and have a string alias. */
    interface WithAlias: Signer {
        val alias: String
    }

    /** Some [Signer]s might have an attestation of some sort */
    interface Attestable<AttestationT: Attestation>: Signer {
        val attestation: AttestationT?
    }

    suspend fun sign(data: SignatureInput): KmmResult<CryptoSignature>

    /**
     * A handle to a [TemporarilyUnlockable] signer that is temporarily unlocked.
     * The handle is only guaranteed to be valid within the scope of the block.
     */
    @OptIn(ExperimentalStdlibApi::class)
    interface UnlockedHandle: AutoCloseable, Signer {
        override val mayRequireUserUnlock: Boolean get() = false
    }

    /**
     * A signer that can be temporarily unlocked.
     * Once unlocked, multiple signing operations can be performed with a single unlock.
     */
    abstract class TemporarilyUnlockable<Handle: UnlockedHandle> : Signer {
        final override val mayRequireUserUnlock: Boolean get() = true

        @HazardousMaterials
        abstract suspend fun unlock(): KmmResult<Handle>

        /**
         * Unlocks the signer, then executes the block with the [UnlockedHandle] as its receiver.
         *
         * The handle's validity is only guaranteed in the block scope.
         */
        @OptIn(ExperimentalStdlibApi::class, HazardousMaterials::class)
        suspend inline fun <reified T> withUnlock(fn: Handle.()->T): KmmResult<T> =
            unlock().mapCatching { it.use(fn) }

        @OptIn(ExperimentalStdlibApi::class, HazardousMaterials::class)
        final override suspend fun sign(data: SignatureInput): KmmResult<CryptoSignature> =
            unlock().transform { h -> h.use { it.sign(data) } }
    }

    companion object {
        operator fun invoke(configure: DSLConfigureFn<EphemeralSigningKeyConfiguration> = null) =
            EphemeralKey(configure).signer()
    }
}

/**
 * Get a verifier for signatures generated by this [Signer].
 * @see SignatureAlgorithm.verifierFor
 */
fun Signer.makeVerifier(configure: ConfigurePlatformVerifier = null) = signatureAlgorithm.verifierFor(publicKey, configure)

/**
 * Gets a platform verifier for signatures generated by this [Signer].
 * @see SignatureAlgorithm.platformVerifierFor
 */
fun Signer.makePlatformVerifier(configure: ConfigurePlatformVerifier = null) = signatureAlgorithm.platformVerifierFor(publicKey, configure)

val Signer.ECDSA.curve get() = publicKey.curve

/**
 * Try to batch sign with this signer.
 * Might fail for unlockable signers that cannot be temporarily unlocked.
 */
suspend inline fun <reified T> Signer.withUnlock(fn: Signer.()->T) =
    when (this.mayRequireUserUnlock) {
        true ->
            if (this is Signer.TemporarilyUnlockable<*>)
                this.withUnlock(fn)
            else
                KmmResult.failure(UnlockFailed("This signer needs authentication for every use"))
        false -> catching { fn(this) }
    }

suspend inline fun Signer.sign(data: ByteArray) = sign(SignatureInput(data))
