{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-oids/3.20.0-PREVIEW/indispensable-oids-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable-oids",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-iosX64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-oids-iosx64-3.20.0-PREVIEW.klib",
          "size": 606283,
          "sha512": "e75f1ad43a592a6cfc2430a0a344ecc6b64f7c95e6e38e78abcf2172d69308784b249f5644efc841cc4f3500c898cc0b2ae17fd99d87bcc817d28c932d246b0d",
          "sha256": "ab2552c213d9d702ea75287a3440fca922c81e9c705daa0098ceff2567483268",
          "sha1": "a1d0cd4cec116720b2f39899ba841cbcdb04f0bb",
          "md5": "d9dcd7d0247c18101fce29559fb2409d"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-oids-iosx64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-oids-iosx64-3.20.0-PREVIEW-sources.jar",
          "size": 87050,
          "sha512": "fc6f1cec4fa7ebc507924ead1b0a626eae184148380f6f0c64f60d234ba1b6532dfb78900478706797fb1cc26205d896dd7d3b290feca56abac0ae5873499ca7",
          "sha256": "e8a4c0b7953f5cb49349bdd5b7cbb26701353f992af01785aba7385d4fc42040",
          "sha1": "b630e3a0a9844af8d0c177f04cbe0519e1fa5039",
          "md5": "c61df4e0a0eff6ba6613137add0bbfb8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-iosx64-3.20.0-PREVIEW-metadata.jar",
          "url": "indispensable-oids-iosx64-3.20.0-PREVIEW-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
