{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-cosef/3.20.0-PREVIEW/indispensable-cosef-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable-cosef",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-cosef-linuxX64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-cosef-linuxx64-3.20.0-PREVIEW.klib",
          "size": 183045,
          "sha512": "4fdecc518325aba127cf7d904947778889a15de3005d6f46d3c9d11acf45532d824b852589a0b1c93b46478531bf020238dc2bc7e0bc7e9f45d1ab9261143ced",
          "sha256": "88517a19b940e429aa30d1c21d3823af8ed5085f363b12c9c1a1898409263c91",
          "sha1": "26208903a4292ec24351715bc9d77a8d715bbbbb",
          "md5": "2d6094ab9d318bf93cdcbfdc962fa722"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-cosef-linuxx64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-cosef-linuxx64-3.20.0-PREVIEW-sources.jar",
          "size": 28704,
          "sha512": "22ffd64377ce9ed685a107a46cb783fa414eafa12e042967a490ac2839ffc9bf33ba8f6e6856a5fcad88b8e8da772722955b2e36e679117b10e08b63252aea24",
          "sha256": "8d707a316871d4a28cd60b1416369b60e2418d82c6383e6fe003dab458d48fcb",
          "sha1": "a719004b082df10f49e36f64553beba740d6bfc3",
          "md5": "5e02234840ffa904888f62ac3b9af9d5"
        }
      ]
    }
  ]
}
