{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-blocking-detection-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-androidNativeArm32Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 5183,
          "sha512": "8562d6e0ebaf88213a8626bcb02320d4862e88fbbde23ebd11d3257c423e719bddd31a05fb70e26b42dda110173755fb184ad794ef12d1b3d3bd3074e821eb4e",
          "sha256": "370ddfbcd3acbb227e3f59652f754ec3039cd262b42e83e30bc8a2c4ab0ca5b9",
          "sha1": "f7d3d981ea200546e582a4d3e9748f22c9dc4bc9",
          "md5": "2f17f68cc3eed918b16a4e9bc08442f1"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 2962,
          "sha512": "6c17f157fe90aecb2cfa4d5a36fc2bb0d9eafe9ac9a07d8a7088c40760198be4c585cb0d80a9b9e56ed842e4d2084b18f104a5817f5778a9ee7129d8d398b239",
          "sha256": "87bbf1704d2b3d6ece29747484afad5289b703d5073838712435ccb340d3d1d8",
          "sha1": "243ebfbee1343a5d4518acf4cc77bde88427c255",
          "md5": "3081b92d35e85f729925f5b3cc46036b"
        }
      ]
    }
  ]
}
