{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.20.0-PREVIEW/supreme-0.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "supreme",
    "version": "0.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosArm64Main-0.20.0-PREVIEW.klib",
          "url": "supreme-iosarm64-0.20.0-PREVIEW.klib",
          "size": 461818,
          "sha512": "1cf731c19c703df61bea9eac456af2f317a42cc9ee4059456ad7678cba302a80444950ae24f6842e75f417a5ca989c2af2abf25715d2ce8d8d6b949c84c3f1fb",
          "sha256": "96c1cfcbdd837cf901b227a1d86d83e0a9795037d68728cb9de566827da56394",
          "sha1": "4c7d28ef17fd901d968dad23d14b6b9eff1c49c9",
          "md5": "d8fd1fbb93935e8f530460323a0909ab"
        },
        {
          "name": "supreme-iosArm64Cinterop-cinteropMain-0.20.0-PREVIEW.klib",
          "url": "supreme-iosarm64-0.20.0-PREVIEW-cinterop-cinterop.klib",
          "size": 27016,
          "sha512": "0ab0ce1409d8448cc56532308d2dfc16ca941468d3459483033b0e8a356d58c3a4ea7728c94a99c07a3d6fc02ef8d0b28c0f5afc7ee8150b8c75884218d499b2",
          "sha256": "6ca4d73717bb0eb67d60c1970ba57440d7f716c7696d7afea567c24e0d419de9",
          "sha1": "6d9be56f91cc89619de272ef43e39bfbdaafa770",
          "md5": "83ee41cd78acae1aac1beb3e71af4674"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "supreme-iosarm64-0.20.0-PREVIEW-sources.jar",
          "url": "supreme-iosarm64-0.20.0-PREVIEW-sources.jar",
          "size": 206090,
          "sha512": "4492a6cff322e597445e922fcd915982bf2bc3fcb568ad36e5f287229e607c74bd26e691d91c95349066072e21d6789b666781c9636152fd773f8e06f4e87f7d",
          "sha256": "4ec8680e2d75acf2a8789c99cf7685d0f3252974dbf1791f4edbfc6eb603a7b6",
          "sha1": "2affdce2d8a61cb1208f7abc948c988983b176f2",
          "md5": "c300e3956f637a148cf525ecc4ccddff"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosarm64-0.20.0-PREVIEW-metadata.jar",
          "url": "supreme-iosarm64-0.20.0-PREVIEW-metadata.jar",
          "size": 42828,
          "sha512": "9e47c69ee1c17c620fe3bd343f8eebdf1e69ebf7ca410a7b0e1618ded3006a0f402e8f282bca177f7bc53f11b606abe516e5f4f52a1d34a93a383e16e306724e",
          "sha256": "273f1d9d5fc33b3d749a55db69db83320afff107e33efdfae130336a526019b6",
          "sha1": "38e2ea335df0f2590d5e540bb291a73317539239",
          "md5": "27c3a8e30ab4f7ca94374670333a1299"
        }
      ]
    }
  ]
}
