{
  "formatVersion": "1.1",
  "component": {
    "group": "Signum",
    "module": "supreme",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-metadata-0.12.0-PREVIEW.jar",
          "url": "supreme-0.12.0-PREVIEW.jar",
          "size": 32214,
          "sha512": "b3bd42e204952d0f76ca4a60872c9486e0d6ef26b57068d0bdf35b497cef3407c2ecb5a0ac40ea99e9241355b972da565d9f50345ced8b9103f065ecbef4cb3d",
          "sha256": "529396ebe9abd17c3536ddabbb30eb54cf063e3b798a434a9fac73af1e2c8223",
          "sha1": "8275583c5fb056bd66f1530d5c968806b16078f3",
          "md5": "6f48ee18c38a218d47089fbae5315225"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "supreme-kotlin-0.12.0-PREVIEW-sources.jar",
          "url": "supreme-0.12.0-PREVIEW-sources.jar",
          "size": 206085,
          "sha512": "ebcf195c9c91c68bccf3909ca5be3912cd6944ee3f2cee0b6e3d896770acb788b74dd9ed96c969fa8e36aa959bf67c82886239d829374e319fe05f12cb7bc657",
          "sha256": "e7918f414358d11d16af15df7416b2e792254400ff9c497901830abeebfc78b9",
          "sha1": "749fe3d7f6cabc808abde6abd875f3a889fdbbc3",
          "md5": "ebe05fa76b147822659f8aff3992849b"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../supreme-android/0.12.0-PREVIEW/supreme-android-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-android",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../supreme-android/0.12.0-PREVIEW/supreme-android-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-android",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../supreme-android/0.12.0-PREVIEW/supreme-android-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-android",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iosarm64/0.12.0-PREVIEW/supreme-iosarm64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iosarm64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iosarm64/0.12.0-PREVIEW/supreme-iosarm64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iosarm64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iosarm64/0.12.0-PREVIEW/supreme-iosarm64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iosarm64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iossimulatorarm64/0.12.0-PREVIEW/supreme-iossimulatorarm64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iossimulatorarm64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iossimulatorarm64/0.12.0-PREVIEW/supreme-iossimulatorarm64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iossimulatorarm64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iossimulatorarm64/0.12.0-PREVIEW/supreme-iossimulatorarm64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iossimulatorarm64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iosx64/0.12.0-PREVIEW/supreme-iosx64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iosx64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iosx64/0.12.0-PREVIEW/supreme-iosx64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iosx64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../supreme-iosx64/0.12.0-PREVIEW/supreme-iosx64-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-iosx64",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../supreme-jvm/0.12.0-PREVIEW/supreme-jvm-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-jvm",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../supreme-jvm/0.12.0-PREVIEW/supreme-jvm-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-jvm",
        "version": "0.12.0-PREVIEW"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../supreme-jvm/0.12.0-PREVIEW/supreme-jvm-0.12.0-PREVIEW.module",
        "group": "Signum",
        "module": "supreme-jvm",
        "version": "0.12.0-PREVIEW"
      }
    }
  ]
}
