{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-oids",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-metadata-3.20.0-PREVIEW.jar",
          "url": "indispensable-oids-3.20.0-PREVIEW.jar",
          "size": 28154,
          "sha512": "00d26607a1ef6383d8bb34e970913a95df1b55f47bb74f04fac0bfe36f0c594a0e6b62e4ada0c5f734b6d46f87b203b61c1f6bd71ae97873c2a8e88ae6a53581",
          "sha256": "4d52e187ba9001f075258f1235468cd0e5278cc6679b6242e3eb3c9d1e582471",
          "sha1": "0e586f393062c35f34de7f02c9a8b351636d0557",
          "md5": "67bc4ffde1bdb40bb4d983e12957337e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "indispensable-oids-kotlin-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-oids-3.20.0-PREVIEW-sources.jar",
          "size": 87050,
          "sha512": "fc6f1cec4fa7ebc507924ead1b0a626eae184148380f6f0c64f60d234ba1b6532dfb78900478706797fb1cc26205d896dd7d3b290feca56abac0ae5873499ca7",
          "sha256": "e8a4c0b7953f5cb49349bdd5b7cbb26701353f992af01785aba7385d4fc42040",
          "sha1": "b630e3a0a9844af8d0c177f04cbe0519e1fa5039",
          "md5": "c61df4e0a0eff6ba6613137add0bbfb8"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-oids-android/3.20.0-PREVIEW/indispensable-oids-android-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-android",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-oids-android/3.20.0-PREVIEW/indispensable-oids-android-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-android",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-oids-android/3.20.0-PREVIEW/indispensable-oids-android-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-android",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativearm32/3.20.0-PREVIEW/indispensable-oids-androidnativearm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativearm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativearm32/3.20.0-PREVIEW/indispensable-oids-androidnativearm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativearm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativearm64/3.20.0-PREVIEW/indispensable-oids-androidnativearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativearm64/3.20.0-PREVIEW/indispensable-oids-androidnativearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativex64/3.20.0-PREVIEW/indispensable-oids-androidnativex64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativex64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativex64/3.20.0-PREVIEW/indispensable-oids-androidnativex64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativex64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativex86/3.20.0-PREVIEW/indispensable-oids-androidnativex86-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativex86",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-androidnativex86/3.20.0-PREVIEW/indispensable-oids-androidnativex86-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-androidnativex86",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iosarm64/3.20.0-PREVIEW/indispensable-oids-iosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iosarm64/3.20.0-PREVIEW/indispensable-oids-iosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iosarm64/3.20.0-PREVIEW/indispensable-oids-iosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-iossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-iossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-iossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iosx64/3.20.0-PREVIEW/indispensable-oids-iosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iosx64/3.20.0-PREVIEW/indispensable-oids-iosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-iosx64/3.20.0-PREVIEW/indispensable-oids-iosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-iosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../indispensable-oids-js/3.20.0-PREVIEW/indispensable-oids-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../indispensable-oids-js/3.20.0-PREVIEW/indispensable-oids-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../indispensable-oids-js/3.20.0-PREVIEW/indispensable-oids-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-oids-jvm/3.20.0-PREVIEW/indispensable-oids-jvm-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-jvm",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-oids-jvm/3.20.0-PREVIEW/indispensable-oids-jvm-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-jvm",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../indispensable-oids-jvm/3.20.0-PREVIEW/indispensable-oids-jvm-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-jvm",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-linuxarm64/3.20.0-PREVIEW/indispensable-oids-linuxarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-linuxarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-linuxarm64/3.20.0-PREVIEW/indispensable-oids-linuxarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-linuxarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-linuxx64/3.20.0-PREVIEW/indispensable-oids-linuxx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-linuxx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-linuxx64/3.20.0-PREVIEW/indispensable-oids-linuxx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-linuxx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-macosarm64/3.20.0-PREVIEW/indispensable-oids-macosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-macosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-macosarm64/3.20.0-PREVIEW/indispensable-oids-macosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-macosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-macosarm64/3.20.0-PREVIEW/indispensable-oids-macosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-macosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-macosx64/3.20.0-PREVIEW/indispensable-oids-macosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-macosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-macosx64/3.20.0-PREVIEW/indispensable-oids-macosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-macosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-macosx64/3.20.0-PREVIEW/indispensable-oids-macosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-macosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-mingwx64/3.20.0-PREVIEW/indispensable-oids-mingwx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-mingwx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-mingwx64/3.20.0-PREVIEW/indispensable-oids-mingwx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-mingwx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvosarm64/3.20.0-PREVIEW/indispensable-oids-tvosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvosarm64/3.20.0-PREVIEW/indispensable-oids-tvosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvosarm64/3.20.0-PREVIEW/indispensable-oids-tvosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-tvossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-tvossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-tvossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvosx64/3.20.0-PREVIEW/indispensable-oids-tvosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvosx64/3.20.0-PREVIEW/indispensable-oids-tvosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-tvosx64/3.20.0-PREVIEW/indispensable-oids-tvosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-tvosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../indispensable-oids-wasm-js/3.20.0-PREVIEW/indispensable-oids-wasm-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-wasm-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../indispensable-oids-wasm-js/3.20.0-PREVIEW/indispensable-oids-wasm-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-wasm-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../indispensable-oids-wasm-js/3.20.0-PREVIEW/indispensable-oids-wasm-js-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-wasm-js",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosarm32/3.20.0-PREVIEW/indispensable-oids-watchosarm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosarm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosarm32/3.20.0-PREVIEW/indispensable-oids-watchosarm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosarm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosarm32/3.20.0-PREVIEW/indispensable-oids-watchosarm32-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosarm32",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosarm64/3.20.0-PREVIEW/indispensable-oids-watchosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosarm64/3.20.0-PREVIEW/indispensable-oids-watchosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosarm64/3.20.0-PREVIEW/indispensable-oids-watchosarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosdevicearm64/3.20.0-PREVIEW/indispensable-oids-watchosdevicearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosdevicearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosdevicearm64/3.20.0-PREVIEW/indispensable-oids-watchosdevicearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosdevicearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosdevicearm64/3.20.0-PREVIEW/indispensable-oids-watchosdevicearm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosdevicearm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-watchossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-watchossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchossimulatorarm64/3.20.0-PREVIEW/indispensable-oids-watchossimulatorarm64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchossimulatorarm64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosx64/3.20.0-PREVIEW/indispensable-oids-watchosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosx64/3.20.0-PREVIEW/indispensable-oids-watchosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosx64",
        "version": "3.20.0-PREVIEW"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../indispensable-oids-watchosx64/3.20.0-PREVIEW/indispensable-oids-watchosx64-3.20.0-PREVIEW.module",
        "group": "at.asitplus.signum",
        "module": "indispensable-oids-watchosx64",
        "version": "3.20.0-PREVIEW"
      }
    }
  ]
}
