{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-wasm-js-3.20.0-PREVIEW.klib",
          "url": "internals-wasm-js-3.20.0-PREVIEW.klib",
          "size": 12644,
          "sha512": "6a8a8af81d2d5a89a0a69b9e215af04e9762967dd61ecfef6bbe475171dcbf63fe0c6d05ec327836252ddf45e366cfb8976fd61c2757783cf02dc5c5568fd38b",
          "sha256": "59f557b2a1f0b47af8824cd222d024076559f7cbdf18644f1b36b368cc415d1f",
          "sha1": "8d7a75e5d1d4602a71b4b125021fc82ffe94a026",
          "md5": "6ead666a8bfca4714ebfa020508c3e6f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-wasm-js-3.20.0-PREVIEW.klib",
          "url": "internals-wasm-js-3.20.0-PREVIEW.klib",
          "size": 12644,
          "sha512": "6a8a8af81d2d5a89a0a69b9e215af04e9762967dd61ecfef6bbe475171dcbf63fe0c6d05ec327836252ddf45e366cfb8976fd61c2757783cf02dc5c5568fd38b",
          "sha256": "59f557b2a1f0b47af8824cd222d024076559f7cbdf18644f1b36b368cc415d1f",
          "sha1": "8d7a75e5d1d4602a71b4b125021fc82ffe94a026",
          "md5": "6ead666a8bfca4714ebfa020508c3e6f"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "internals-wasm-js-3.20.0-PREVIEW-sources.jar",
          "url": "internals-wasm-js-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    }
  ]
}
