[versions]
kotlin = "2.4.0"
agp = "9.0.1"
core = "1.5.0"
kotlinxIoCore = "0.9.0"
kotlinxMetadataJvm = "0.9.0"
multibase = "1.3.0"
bignum = "0.3.10"
jose = "9.31"
kotlinpoet = "2.2.0"
kotlincryptoRandom = "0.6.0"
asp = "20260722"
classgraph = "4.8.184"
bouncycastle= "1.85"
testballoon = "1.0.1-K2.4.0"
serialization = "1.11.0"
cidre = "0.4.0"
urikmp = "0.0.20"
awesn1 = "0.5.0"
modulator = "0.1.0"

[libraries]
bignum = { group = "com.ionspin.kotlin", name = "bignum", version.ref = "bignum" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIoCore" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }
jose = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "jose" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
multibase = { module = "at.asitplus:multibase", version.ref = "multibase" }
securerandom = { module = "org.kotlincrypto.random:crypto-rand", version.ref = "kotlincryptoRandom" }
asp = { module = "at.asitplus.gradle:k2", version.ref = "asp" }
classgraph = { group = "io.github.classgraph", name = "classgraph", version.ref = "classgraph" }
awesn1-crypto = {module = "at.asitplus.awesn1:crypto", version.ref= "awesn1"}
awesn1-oids = {module = "at.asitplus.awesn1:oids", version.ref= "awesn1"}
awesn1-io = {module = "at.asitplus.awesn1:kxs-io", version.ref= "awesn1"}
cidre = { module = "at.asitplus:cidre", version.ref = "cidre"}
urikmp = {module = "com.eygraber:uri-kmp", version.ref = "urikmp"}

#for build logic conventions plugin, as it needs the artefact, not the plugin ID
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
modulator = { module = "at.asitplus:gradle-modulator", version.ref = "modulator" }

[plugins]
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }
