{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable/3.20.0-PREVIEW/indispensable-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "Signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-linuxX64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-linuxx64-3.20.0-PREVIEW.klib",
          "size": 548533,
          "sha512": "221c7bd2afedf2def2e4ccf4bdeefce756a9dc23a05afe7f934183c743423b4d7a5709b7d5efb8bc3a43068fa8be4675c1e073c8aa523ea7e9dc6e8f92901b73",
          "sha256": "3fbffa90217d5f4883c552f2d457306f3b3f5e801d9ccff0decde84c48fd4b56",
          "sha1": "92e7d55fc50a5d85eefb345fbbc286d9e2ef9c4c",
          "md5": "ed6b482e4fa4f0bb1d890d020f4747e8"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-linuxx64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-linuxx64-3.20.0-PREVIEW-sources.jar",
          "size": 107467,
          "sha512": "aa0f3b0d5618417f5e786715971f6489a6005c7103d6308804094f881017708f7e2ac1957138bf46b2e6cddf2d07f5198dad4775228d61d3f70e69b19046fe0b",
          "sha256": "97b0cd48c5a4734e9d1f334648bdd4dc7b54fbacdc7c3d0dbaaa357656db34d6",
          "sha1": "b275f440776c4545d0f449aa70eb3af2649e958a",
          "md5": "79c9f270c703be3557e1fef2bd63e288"
        }
      ]
    }
  ]
}
