{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-josef/3.20.0-PREVIEW/indispensable-josef-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable-josef",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-josef-androidNativeX86Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-josef-androidnativex86-3.20.0-PREVIEW.klib",
          "size": 202428,
          "sha512": "0ad8642d01b595c93f5607fdaf240e346807d1698cbaea18d485a64da8fcf2ea4ac9ef73a9a48b88d6357149ea7d3d3bbf481cee3db1b1978a8854f572170f6a",
          "sha256": "9dbd952bd14dc0d280d0ab6e11bfd6ff3c8ffc703cee33076689985806c0c92b",
          "sha1": "2dcee645a50a47b19df90ed297e63aa7470ac792",
          "md5": "04ca9bd7e9b1fa9e34313c689b8b5c9e"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-josef-androidnativex86-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-josef-androidnativex86-3.20.0-PREVIEW-sources.jar",
          "size": 34428,
          "sha512": "17bfead8e989cf8f12a249b5d0c0a1fc565ae8488186e84e54b7c3bdcbc0d808802c3f81595e92be734e913c2e3d54c3c797d187fd20eb643609bcacec398624",
          "sha256": "86eb664faeffe738a316ed0aa5f17726e1cd1a4280a3cf31599c319b2f241704",
          "sha1": "fe10a771dd427c76953c4863705a3d7e0cf0cba6",
          "md5": "e2b88bb749c78f522a11df075bc731a5"
        }
      ]
    }
  ]
}
