{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-js-3.20.0-PREVIEW.klib",
          "url": "internals-js-3.20.0-PREVIEW.klib",
          "size": 12639,
          "sha512": "a430eb34fe12667b491cd77afdeb0c93a26f49dcb88f0f93efdcabcd25963a205e635de551a6f7261f6f34bc9513b0a2dd7fe0a64938f6cbac18310ed913ab42",
          "sha256": "be6f4cc7a931f10c17aec8744420617d280f085ca8f1e54778c827905a260420",
          "sha1": "70ae5bd059769d045ed0f604923b1bc42bdba787",
          "md5": "b78ae59c93f9abd617d12e7d972bfc96"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-js-3.20.0-PREVIEW.klib",
          "url": "internals-js-3.20.0-PREVIEW.klib",
          "size": 12639,
          "sha512": "a430eb34fe12667b491cd77afdeb0c93a26f49dcb88f0f93efdcabcd25963a205e635de551a6f7261f6f34bc9513b0a2dd7fe0a64938f6cbac18310ed913ab42",
          "sha256": "be6f4cc7a931f10c17aec8744420617d280f085ca8f1e54778c827905a260420",
          "sha1": "70ae5bd059769d045ed0f604923b1bc42bdba787",
          "md5": "b78ae59c93f9abd617d12e7d972bfc96"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "internals-js-3.20.0-PREVIEW-sources.jar",
          "url": "internals-js-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    }
  ]
}
