{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-js-3.20.0-PREVIEW.klib",
          "url": "internals-js-3.20.0-PREVIEW.klib",
          "size": 12649,
          "sha512": "68a4a3b0dd8edb906f682a4b1ea58736e01cfd213ab6565398d9cd424f0681cf15737888aedef02f3ee05fb10e7c93ed8657b9243e3d8a0ae8e9831e41f48168",
          "sha256": "e75717f40e4e7f01a0e1102ff8471e1cea099d4c0582aa1e6cbc963423b69e0a",
          "sha1": "4bcd85af19e01834ec2894bf50264ef1730370e8",
          "md5": "08ed73e384b93b6c454404acb019ba07"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-js-3.20.0-PREVIEW.klib",
          "url": "internals-js-3.20.0-PREVIEW.klib",
          "size": 12649,
          "sha512": "68a4a3b0dd8edb906f682a4b1ea58736e01cfd213ab6565398d9cd424f0681cf15737888aedef02f3ee05fb10e7c93ed8657b9243e3d8a0ae8e9831e41f48168",
          "sha256": "e75717f40e4e7f01a0e1102ff8471e1cea099d4c0582aa1e6cbc963423b69e0a",
          "sha1": "4bcd85af19e01834ec2894bf50264ef1730370e8",
          "md5": "08ed73e384b93b6c454404acb019ba07"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "internals-js-3.20.0-PREVIEW-sources.jar",
          "url": "internals-js-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    }
  ]
}
