{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.12.0-PREVIEW/supreme-0.12.0-PREVIEW.module",
    "group": "Signum",
    "module": "supreme",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme.aar",
          "url": "supreme-android-0.12.0-PREVIEW.aar",
          "size": 496137,
          "sha512": "011f23a07f0cd7be4e4ed039cca45775d37f76ca2803ec2df8b1a857c80c708126d72b4b9df67756176adb2a52f53e8ff0e20b7d47f2cdef42c9d81e291f553f",
          "sha256": "962a432481330ae8f6c356fc15feb3ecc24cbea137597149211a344fca72e478",
          "sha1": "ef79a1ab7b041b8bafaa4bd41c33496d073a1e9e",
          "md5": "7f84359dcd49027673b659cb2ae05825"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme.aar",
          "url": "supreme-android-0.12.0-PREVIEW.aar",
          "size": 496137,
          "sha512": "011f23a07f0cd7be4e4ed039cca45775d37f76ca2803ec2df8b1a857c80c708126d72b4b9df67756176adb2a52f53e8ff0e20b7d47f2cdef42c9d81e291f553f",
          "sha256": "962a432481330ae8f6c356fc15feb3ecc24cbea137597149211a344fca72e478",
          "sha1": "ef79a1ab7b041b8bafaa4bd41c33496d073a1e9e",
          "md5": "7f84359dcd49027673b659cb2ae05825"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "supreme-android-0.12.0-PREVIEW-sources.jar",
          "url": "supreme-android-0.12.0-PREVIEW-sources.jar",
          "size": 60695,
          "sha512": "734918cd55fb5c5d9b8af096ee276d203e599748b60e6ced1707ad78b7d66787e1e235c62e74824f33176ab16633337b8ef6fc079b14a33c1785662b372d8ba1",
          "sha256": "18fb11e7a71f648d72eba219c2d345cad4a9fb8e1cc16de2617a4b3b8ea3863a",
          "sha1": "bb60dd35befefd2a5e02c1a075ab61fd679f5f7b",
          "md5": "a8dc8263dd6e2e889bf053d7adf6cf7a"
        }
      ]
    }
  ]
}
