{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-cosef-versionCatalog",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "indispensable-cosef-versionCatalog-3.20.0-PREVIEW.toml",
          "url": "indispensable-cosef-versionCatalog-3.20.0-PREVIEW.toml",
          "size": 2387,
          "sha512": "770a34af7505a1351d423ac1e1a4ca1a84d83ca45a6f10e879908cc5c4e855a18141d5991b37e7d1e3b08d4d5acea5a8ef683d7c9cfd3183db17296b64670480",
          "sha256": "22a0de4740ac433bba42cb099d9b4d1f46541c919420966b9475a123cd7d6a5b",
          "sha1": "86aba393f288af6c91647eb6da87d438676f7173",
          "md5": "aebf2080a6dea9c3ef377a75f95a372e"
        }
      ]
    }
  ]
}
