{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-blocking-detection-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-wasm-wasi-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-wasm-wasi-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 4983,
          "sha512": "a61c1d015b4cd6e1088a51f240f0d4512db66538e2d068d4820267a297b3de3936cdcf2d952e56d6ca79ccbbe520ded26f507e79ed317236c9a4ced36a26f78b",
          "sha256": "238a2f98e14a89dd067f0781f4b8ec18dc0a181ac6f0d491a5440be275cb2da1",
          "sha1": "dd3c2877861e19352a4238f8c93a339e1bc6b20f",
          "md5": "222a0fb67d528d226120ec8e2e7de78a"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-wasm-wasi-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-wasm-wasi-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 4983,
          "sha512": "a61c1d015b4cd6e1088a51f240f0d4512db66538e2d068d4820267a297b3de3936cdcf2d952e56d6ca79ccbbe520ded26f507e79ed317236c9a4ced36a26f78b",
          "sha256": "238a2f98e14a89dd067f0781f4b8ec18dc0a181ac6f0d491a5440be275cb2da1",
          "sha1": "dd3c2877861e19352a4238f8c93a339e1bc6b20f",
          "md5": "222a0fb67d528d226120ec8e2e7de78a"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-wasm-wasi-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-wasm-wasi-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 2962,
          "sha512": "6c17f157fe90aecb2cfa4d5a36fc2bb0d9eafe9ac9a07d8a7088c40760198be4c585cb0d80a9b9e56ed842e4d2084b18f104a5817f5778a9ee7129d8d398b239",
          "sha256": "87bbf1704d2b3d6ece29747484afad5289b703d5073838712435ccb340d3d1d8",
          "sha1": "243ebfbee1343a5d4518acf4cc77bde88427c255",
          "md5": "3081b92d35e85f729925f5b3cc46036b"
        }
      ]
    }
  ]
}
