{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-versionCatalog",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "indispensable-versionCatalog-3.20.0-PREVIEW.toml",
          "url": "indispensable-versionCatalog-3.20.0-PREVIEW.toml",
          "size": 2889,
          "sha512": "51d9a2c6ed45ab1a2862ef536333371f40f2f151bfd51e77913c6328921ddaccd0583f7fca114f3b04563b1ae84c969e3cabe241a8f9a49cbfb0e7593dcb67e5",
          "sha256": "350f2ec8b790002332de5033c70f89e2b7047071a64ec3b4bbf446bc0a456731",
          "sha1": "61ea38f43f4b62362be0c94e1dfceb13b40ce360",
          "md5": "dcbc6de7fbce12cf67982643e61790e4"
        }
      ]
    }
  ]
}
