{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-cosef/3.20.0-PREVIEW/indispensable-cosef-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable-cosef",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-cosef-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-cosef-js-3.20.0-PREVIEW.klib",
          "size": 176763,
          "sha512": "c8ab6b21e174285033ccfb48f8e449780f320c8fe877408d4b2d6b8e3cd8edbf3957906a27c2e27ae0c8d74ea35a754dabde0d89468d08b54bc20dfcd29f9107",
          "sha256": "0ec4637dcb0af71db5ebd955e985b3cfd19db4d5e1b3938bdfc347b1efa0a958",
          "sha1": "4246729152fe3c71a7683b1f1868eb1bf83904f6",
          "md5": "25af5ee1e6ceb8d92ad52a2a3ad35b05"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-cosef-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-cosef-js-3.20.0-PREVIEW.klib",
          "size": 176763,
          "sha512": "c8ab6b21e174285033ccfb48f8e449780f320c8fe877408d4b2d6b8e3cd8edbf3957906a27c2e27ae0c8d74ea35a754dabde0d89468d08b54bc20dfcd29f9107",
          "sha256": "0ec4637dcb0af71db5ebd955e985b3cfd19db4d5e1b3938bdfc347b1efa0a958",
          "sha1": "4246729152fe3c71a7683b1f1868eb1bf83904f6",
          "md5": "25af5ee1e6ceb8d92ad52a2a3ad35b05"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "indispensable-cosef-js-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-cosef-js-3.20.0-PREVIEW-sources.jar",
          "size": 28704,
          "sha512": "22ffd64377ce9ed685a107a46cb783fa414eafa12e042967a490ac2839ffc9bf33ba8f6e6856a5fcad88b8e8da772722955b2e36e679117b10e08b63252aea24",
          "sha256": "8d707a316871d4a28cd60b1416369b60e2418d82c6383e6fe003dab458d48fcb",
          "sha1": "a719004b082df10f49e36f64553beba740d6bfc3",
          "md5": "5e02234840ffa904888f62ac3b9af9d5"
        }
      ]
    }
  ]
}
