package at.asitplus.signum.supreme.validate

import at.asitplus.signum.ExperimentalPkiApi
import at.asitplus.signum.HazardousMaterials
import at.asitplus.signum.indispensable.asn1.Asn1Exception
import at.asitplus.signum.indispensable.asn1.KnownOIDs
import at.asitplus.signum.indispensable.asn1.ObjectIdentifier
import at.asitplus.signum.indispensable.asn1.anyPolicy
import at.asitplus.signum.indispensable.pki.CertificateChain
import at.asitplus.signum.indispensable.pki.X509Certificate
import at.asitplus.signum.indispensable.pki.leaf
import at.asitplus.signum.indispensable.pki.root
import kotlin.contracts.ExperimentalContracts
import kotlin.contracts.contract
import kotlin.coroutines.cancellation.CancellationException


/**
 * Represents the result of validating a certificate chain.
 */
sealed class CertificateValidationResult {

    /** Indicates whether the certificate chain is fully valid (no validator failures). */
    @OptIn(ExperimentalContracts::class)
    val isValid: Boolean
        get() {
            contract {
                returns(true) implies (this@CertificateValidationResult is Success)
                returns(false) implies (this@CertificateValidationResult is Failure || this@CertificateValidationResult is BuildPathFailure)
            }
            return this is Success
        }

    companion object {
        internal operator fun invoke(
            rootPolicyNode: PolicyNode?,
            subject: X509Certificate,
            validatorFailures: List<ValidatorFailure>
        ) = if (validatorFailures.isNotEmpty()) {
            Failure(validatorFailures)
        } else Success(rootPolicyNode, subject)
    }

    data class Success(val rootPolicyNode: PolicyNode?, val subject: X509Certificate) : CertificateValidationResult()
    data class Failure(val validatorFailures: List<ValidatorFailure>) : CertificateValidationResult() {
        init {
            require(validatorFailures.isNotEmpty()) { "Certificate validation failure must not be empty" }
        }
    }
    data class BuildPathFailure(
        val chainFailures: Map<CertificateChain, Failure>
    ) : CertificateValidationResult()
}

/**
 * Represents a failure encountered by a specific validator during certificate chain validation.
 */
data class ValidatorFailure(
    val validatorName: String,
    val validator: CertificateChainValidator? = null,
    val errorMessage: String,
    val cause: Throwable? = null
)

/**
 * Represents a factory for creating certificate validators from a given certificate chain
 * and a validation context. A factory is needed because validation is inherently stateful and individual
 * validators carry mutable state.
 *
 * @param generate A function that takes a `CertificateChain` and a `CertificateValidationContext`,
 *                 and returns a list of `CertificateValidator` instances to be applied.
 */
fun interface ValidatorFactory {
    fun CertificateChain.generate(
        context: CertificateValidationContext
    ): List<CertificateChainValidator>

    companion object {
        val RFC5280: ValidatorFactory =
            ValidatorFactory { context -> defineRFC5280Validators() }
    }
}


/**
 * Performs a custom, potentially unsafe validation of this [AnchoredCertificateChain] using the provided [validatorFactory].
 *
 * This function executes all validators generated by the [validatorFactory]
 * It does not automatically enforce RFC 5280 compliance — any custom validators can be provided
 *
 * This functions ignores list of trust anchors in the context, it only uses [context.selectedTrustAnchor] if present
 *
 * @return a [CertificateValidationResult] containing the resulting policy tree and
 * the end-entity certificate, or a list of [ValidatorFailure]s for a chain that failed to validate.
 *
 * @throws Asn1Exception on structurally invalid input
 */
@OptIn(HazardousMaterials::class)
@ExperimentalPkiApi
suspend fun AnchoredCertificateChain.validate(
    validatorFactory: ValidatorFactory,
    context: CertificateValidationContext = CertificateValidationContext()
): CertificateValidationResult {

    val processingChain =
        if (context.allowIncludedTrustAnchor && trustAnchor.cert?.let { it == chain.root } == true) {
            AnchoredCertificateChain(chain.dropLast(1), trustAnchor)
        } else {
            this
        }
    val validators = with(validatorFactory) { processingChain.chain.generate(context) }
    val validatorFailures = mutableListOf<ValidatorFailure>()
    val checkedCriticalExtensions: MutableMap<X509Certificate, MutableSet<ObjectIdentifier>> =
        processingChain.chain.associateWith { mutableSetOf<ObjectIdentifier>() }
            .toMutableMap()

    validators.forEach { currValidator ->
        try {
            val result = currValidator.validate(processingChain, context)
            for ((cert, oids) in result) {
                checkedCriticalExtensions[cert]?.addAll(oids)
            }
        } catch (e: Throwable) {
            validatorFailures.add(
                ValidatorFailure(
                    currValidator::class.simpleName!!,
                    currValidator,
                    e.message ?: "Validation failed.",
                    e
                )
            )
        }
    }
    verifyCriticalExtensions(checkedCriticalExtensions, validatorFailures)
    return CertificateValidationResult((validators.find { it is PolicyValidator } as? PolicyValidator)?.rootNode,
        this.chain.leaf,
        validatorFailures)
}

/**
 * Attempts to construct a certification path for this [CertificateChain] using the trust anchors
 * provided in the [context], and validates each candidate chain using [validate].
 *
 * If no candidate chain validates successfully, the failures from all attempted chains are collected
 * and returned as a [CertificateValidationResult.BuildPathFailure].
 *
 * Unlike [validate], this function does not require a preselected trust anchor and will attempt
 * validation against all applicable trust anchors available in [CertificateValidationContext.trustAnchors].
 *
 *
 * @return
 * - [CertificateValidationResult.Success] if a valid certification path is found
 * - [CertificateValidationResult.BuildPathFailure] if no candidate chain validates successfully
 */
@OptIn(ExperimentalPkiApi::class)
suspend fun CertificateChain.buildPathAndValidate(
    validatorFactory: ValidatorFactory,
    context: CertificateValidationContext = CertificateValidationContext()
): CertificateValidationResult {
    val candidateChains = TrustAnchorChainConstructor().buildChains(this, context)
    val aggregatedFailures = mutableMapOf<CertificateChain, CertificateValidationResult.Failure>()

    for (anchoredChain in candidateChains) {
        val validationResult = anchoredChain.validate(validatorFactory, context)

        when (validationResult) {
            is CertificateValidationResult.Success -> return validationResult
            is CertificateValidationResult.Failure -> {
                aggregatedFailures[anchoredChain.chain] = validationResult
            }
            is CertificateValidationResult.BuildPathFailure -> {
                error("Unexpected BuildPathFailure from validate(): $validationResult")
            }
        }
    }

    return CertificateValidationResult.BuildPathFailure(aggregatedFailures)
}

/**
 * Performs an RFC 5280-compliant validation of this [AnchoredCertificateChain] using default validators.
 *
 * This function automatically adds all mandatory validators required for standard X.509
 * path validation according to RFC 5280, including:
 * [PolicyValidator] – for certificate policy processing
 * [NameConstraintsValidator] – for name constraint enforcement
 * [KeyUsageValidator] – for key usage and extended key usage checks
 * [BasicConstraintsValidator] – for CA and path length validation
 * [ChainValidator] – for signature chain integrity
 * [TimeValidityValidator] – for certificate validity period
 * [CertValidityValidator] – for checking whether the certificate is constructed correctly, since some components are decoded too leniently
 * [KeyIdentifierValidator] is added to validate Subject and Authority key identifiers
 *
 * Validation results are collected rather than throwing exceptions
 *
 * @return a [CertificateValidationResult] containing the resulting policy tree and
 * the end-entity certificate, or a list of [ValidatorFailure]s for a chain that failed to validate.
 *
 * @throws Asn1Exception on structurally invalid input
 */
@ExperimentalPkiApi
suspend fun AnchoredCertificateChain.validate(
    context: CertificateValidationContext = CertificateValidationContext()
): CertificateValidationResult = validate(ValidatorFactory.RFC5280, context)

/**
 * Performs an RFC 5280-compliant validation of this [CertificateChain] using default validators.
 */
@OptIn(ExperimentalPkiApi::class)
suspend fun CertificateChain.buildPathAndValidate(
    context: CertificateValidationContext = CertificateValidationContext()
): CertificateValidationResult = buildPathAndValidate(ValidatorFactory.RFC5280, context)

/** Constructs list of default validator used in RFC5280 validation based on [context] */
private fun defineRFC5280Validators(): List<CertificateChainValidator> =
    listOf(
        PolicyValidator(),
        CertValidityValidator(),
        NameConstraintsValidator(),
        KeyUsageValidator(),
        BasicConstraintsValidator(),
        ChainValidator(),
        TimeValidityValidator(),
        KeyIdentifierValidator()
    )

/**
 * Checks if there are any unhandled critical extensions remaining,
 * which would indicate that the current validators do not support them.
 */
private fun verifyCriticalExtensions(
    checkedCriticalExtensions: MutableMap<X509Certificate, MutableSet<ObjectIdentifier>>,
    failures: MutableList<ValidatorFailure>) {
    checkedCriticalExtensions.forEach { (cert, criticalExtensions) ->
        val unsupportedCriticalExtensions = cert.criticalExtensionOids - criticalExtensions
        if (unsupportedCriticalExtensions.isNotEmpty() && failures.none { it.validatorName == "CriticalCertificateExtensions" }) {
            failures.add(
                ValidatorFailure(
                    validatorName = "CriticalCertificateExtensions",
                    errorMessage = "Unsupported critical extensions: $unsupportedCriticalExtensions",
                )
            )
        }
    }
}

