{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-core/0.7.1-K2.3.0-SNAPSHOT/testBalloon-framework-core-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-core",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-shared",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 141994,
          "sha512": "e92316bb5530b5297c9c5a3585bc97612fbcccbc3aee08b1116d0e9a3f6c525eed6009a5a942ca07ea2b6a997444a54d46c9efdde676b7db389b5b5f6f349e3a",
          "sha256": "1db6f5e91d5a0e42ca3c202af579ba22f3c3fe9e41f2a3682e93a400d47e3e23",
          "sha1": "ec32f31da6158b82c83185a67115b77a2174f30a",
          "md5": "32a6c8a58a941a14cd0ba095124fd72f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-shared",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-core-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-core-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 141994,
          "sha512": "e92316bb5530b5297c9c5a3585bc97612fbcccbc3aee08b1116d0e9a3f6c525eed6009a5a942ca07ea2b6a997444a54d46c9efdde676b7db389b5b5f6f349e3a",
          "sha256": "1db6f5e91d5a0e42ca3c202af579ba22f3c3fe9e41f2a3682e93a400d47e3e23",
          "sha1": "ec32f31da6158b82c83185a67115b77a2174f30a",
          "md5": "32a6c8a58a941a14cd0ba095124fd72f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "testBalloon-framework-core-js-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-core-js-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 43990,
          "sha512": "d1085b1ef8b3a62c4619ea64b252034d2ccb4d0b3a70779c297ab30040e006dfca142246be80a777bca6b6402d7bfdfc249d15548249b63aa951748d8d148fca",
          "sha256": "52b64581018a368413fda68858ab530dcc5359f4d284c2b654f3ffceba43e65e",
          "sha1": "cc835bc8bff2805bb88b5bc6398da5997ab01d56",
          "md5": "2d6095893783cc216b3d50ccd7da7362"
        }
      ]
    }
  ]
}
