{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "internals-versionCatalog",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "internals-versionCatalog-3.20.0-PREVIEW.toml",
          "url": "internals-versionCatalog-3.20.0-PREVIEW.toml",
          "size": 2178,
          "sha512": "32bbe31245a831cc31f637a18fea65c1b97eec50f0561e85a261ae9de707f86048546759eec87b76af4fbc253574037975783d4445d32cb70164ef2211323eea",
          "sha256": "31609596971f0c956fadf36e7eec1b753a42a50620257310f9d0ed712b7950a5",
          "sha1": "e15ad46ba719b1a2e6b503373a1a615832706e36",
          "md5": "959c251e834308adfb34c20996762381"
        }
      ]
    }
  ]
}
