{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable/3.20.0-PREVIEW/indispensable-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-iosArm64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-iosarm64-3.20.0-PREVIEW.klib",
          "size": 560789,
          "sha512": "5818a1b1d122068c7058a16a26f1f5101b28dfdd15622949ce014f49a53cf20ae39e7f897eeba5f81541b26cf4a79ef239730a06afd0ead57d6c50cfe8def2a4",
          "sha256": "c8973ec80a7ea9fbdc9301954ee31fbff9c041be04b19c2c849733fe858dcc8f",
          "sha1": "a05af7d45260c0014f83aa390a5ba6605021c0a3",
          "md5": "eacddcf7a09dde05627a167ba41e8112"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-iosarm64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-iosarm64-3.20.0-PREVIEW-sources.jar",
          "size": 109020,
          "sha512": "348f2a577de5d3e643370bad54114347e76e8ccb6c5d359cf69bd853b2736e82b59d19d338ef05a2c00be5731240ec86780f451d0bd6ee99df97e461cccabf41",
          "sha256": "dcb3b33fcd37233c143496e21dd69d2b92d22b3c9f6c28a85101239f2b699a41",
          "sha1": "e4d67ab5084baea422c67d9d629810f2c87b82ea",
          "md5": "6d166763598f4a1feed7d332032c8e0c"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-iosarm64-3.20.0-PREVIEW-metadata.jar",
          "url": "indispensable-iosarm64-3.20.0-PREVIEW-metadata.jar",
          "size": 2872,
          "sha512": "ae3c19b2936a8df637cb70436be85fe395404a5d3128de2b5a75c6fa4c740824e66c55a1444f58696df67703347b99a9fd8ed64a947efa819c49a95f92e790ba",
          "sha256": "77e4c60844dfc9c413e198a40a80441a40cc26bddcdb12e47f600c440556d007",
          "sha1": "c8c058084d098da46bee037119bf221dbdecfcb1",
          "md5": "5d02f47004418a89b15ae962a9bd03bc"
        }
      ]
    }
  ]
}
