{
  "formatVersion": "1.1",
  "component": {
    "group": "at.asitplus.signum",
    "module": "indispensable-oids-versionCatalog",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "indispensable-oids-versionCatalog-3.20.0-PREVIEW.toml",
          "url": "indispensable-oids-versionCatalog-3.20.0-PREVIEW.toml",
          "size": 1920,
          "sha512": "fc7daab48b6a6c1a06cc1325d833baaef0210f23818cb89a227a52c549aabf1c4badc7e0131d4cfa64de2d85cf76e829b11bb166dc1cbcfb310c1ec092c42106",
          "sha256": "381103f1eaf7cc313b057e85521e3100253926dc0dc89e43b1cbffaf50f7fcf7",
          "sha1": "aec0b5307f1e6455e7b12656a75702730d072fc1",
          "md5": "076a752580b27e75abb2d725c051e347"
        }
      ]
    }
  ]
}
