{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-blocking-detection-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-watchosArm32Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-blocking-detection-watchosarm32-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 5184,
          "sha512": "70ddd06df18fa6248d02becf40780b6dc1348e9f16e3d9ef2d56e9f08905a7e563effb563081cb5a6f5a2d26e034e82ae155e7a69aef53705545c13efd618fb4",
          "sha256": "18a8a22b0796d858f5e036f90bd1ca4237f5e3713c46896d6c352ecddbb64f65",
          "sha1": "e4e3ea54b697ce8818af16ed49452e9fd0be09bd",
          "md5": "29e87a2033700b8713e91c469f2fc0b9"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-watchosarm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-watchosarm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 2962,
          "sha512": "6c17f157fe90aecb2cfa4d5a36fc2bb0d9eafe9ac9a07d8a7088c40760198be4c585cb0d80a9b9e56ed842e4d2084b18f104a5817f5778a9ee7129d8d398b239",
          "sha256": "87bbf1704d2b3d6ece29747484afad5289b703d5073838712435ccb340d3d1d8",
          "sha1": "243ebfbee1343a5d4518acf4cc77bde88427c255",
          "md5": "3081b92d35e85f729925f5b3cc46036b"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-watchosarm32-0.7.1-K2.3.0-SNAPSHOT-metadata.jar",
          "url": "testBalloon-integration-blocking-detection-watchosarm32-0.7.1-K2.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
