{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-watchosX64Main-3.20.0-PREVIEW.klib",
          "url": "internals-watchosx64-3.20.0-PREVIEW.klib",
          "size": 12895,
          "sha512": "8b34d33dafc79a2f977ec34050c8a6db8ec1d1ae185bb3e7d31b5cb9b6d3db41c28105596530d5a4c6d04372714ce974022f9d7adbaaed44455faa3867b942ed",
          "sha256": "faa7cb7b2fef721da9b041b3bb58ab2723f97fc7cdcccc35cadba3ffc60b3be3",
          "sha1": "652c708070fb96fb4fd585a1cd272bae6a50af8d",
          "md5": "1560d15df0d8a6fcba619058b33e4cdf"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "internals-watchosx64-3.20.0-PREVIEW-sources.jar",
          "url": "internals-watchosx64-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-watchosx64-3.20.0-PREVIEW-metadata.jar",
          "url": "internals-watchosx64-3.20.0-PREVIEW-metadata.jar",
          "size": 3911,
          "sha512": "1ee6395381e3a560424055864bc433ceb883e0deabff6fcdcec9b01957344cc8e818a6a1be73fcbfdb3d91f0e38b5667b20db9a391742636e121cf5107dab52a",
          "sha256": "e65a252f779a004d9643b0c89e5f4cf6712fd386c236f5041fc674ba409a9d59",
          "sha1": "11f59658e6c68b50a204cebb5c77726fee45deae",
          "md5": "1cf423e1c70d5e3f80cc9d585fbf4b0d"
        }
      ]
    }
  ]
}
