{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-cosef/3.20.0-PREVIEW/indispensable-cosef-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable-cosef",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-cbor",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-cosef-androidNativeArm64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-cosef-androidnativearm64-3.20.0-PREVIEW.klib",
          "size": 183070,
          "sha512": "952202d00669aadea4a5b7ab781f93bc64dfac4c9ea6c62acc19fc7b59563205447d9b2b70656c2fc492fd2028257c58f906b57d38ed5e58dcd0b0aba1a3a0ca",
          "sha256": "e327482320af6f26a95ad2ae0043144981bc319d7bc9eff8bfc2b43d949d7821",
          "sha1": "759d12d9e537d811fa401838afefc783cee5950d",
          "md5": "94405350847af850c173955e8f7879a5"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-cosef-androidnativearm64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-cosef-androidnativearm64-3.20.0-PREVIEW-sources.jar",
          "size": 28704,
          "sha512": "22ffd64377ce9ed685a107a46cb783fa414eafa12e042967a490ac2839ffc9bf33ba8f6e6856a5fcad88b8e8da772722955b2e36e679117b10e08b63252aea24",
          "sha256": "8d707a316871d4a28cd60b1416369b60e2418d82c6383e6fe003dab458d48fcb",
          "sha1": "a719004b082df10f49e36f64553beba740d6bfc3",
          "md5": "5e02234840ffa904888f62ac3b9af9d5"
        }
      ]
    }
  ]
}
