{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-linuxX64Main-3.20.0-PREVIEW.klib",
          "url": "internals-linuxx64-3.20.0-PREVIEW.klib",
          "size": 12874,
          "sha512": "c047262b2331104925aa6407523bc6b626e7d4001e195515320888005c40958ffd3c396082734a425a2b897973fdaad5444fa18974f83502abeff0639179dd6a",
          "sha256": "d48b7e2973aeb4ae75d91c1d3c8ae677994526ddc30b7ebb64e81b03587bc2ac",
          "sha1": "8d4cf78de5c4ac48a8348cf364d0f9490b3dded5",
          "md5": "541011ac41e81f95ee30ed24a127271f"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "internals-linuxx64-3.20.0-PREVIEW-sources.jar",
          "url": "internals-linuxx64-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    }
  ]
}
