{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.12.0-PREVIEW/supreme-0.12.0-PREVIEW.module",
    "group": "Signum",
    "module": "supreme",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosSimulatorArm64Main-0.12.0-PREVIEW.klib",
          "url": "supreme-iossimulatorarm64-0.12.0-PREVIEW.klib",
          "size": 461849,
          "sha512": "5598e4428dc01f848aea2f1a484339482082e022811b3c36c02205269af9935a3fc921041cf339f1e3877438703ffd56eeddcba378798e5d66579665bae91c4b",
          "sha256": "292cca7cdb5291d94aebf37a43b9574de174fcdf0d9a68682e4e193d2df10002",
          "sha1": "bada0ec600633d27c8a2e804c71c91c23d0bae58",
          "md5": "45007b496014a727d964286b054d81ad"
        },
        {
          "name": "supreme-iosSimulatorArm64Cinterop-cinteropMain-0.12.0-PREVIEW.klib",
          "url": "supreme-iossimulatorarm64-0.12.0-PREVIEW-cinterop-cinterop.klib",
          "size": 42970,
          "sha512": "6142f5235121d73334d64aacb30ef00f4791e34c4966ceff074540f22265fd6575bce67cda39d8419eb46aa501405cf11a12aaf8fd26a7aa4b91e83015c08219",
          "sha256": "0d66ec36fb948ea59f4d81c1ee49c61d695aecb075d8c8a389a9ef263475d0b6",
          "sha1": "c750af125e20b374c985bc38558c7da07964cc78",
          "md5": "8c831ec9bb049585b0604a692831e151"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "supreme-iossimulatorarm64-0.12.0-PREVIEW-sources.jar",
          "url": "supreme-iossimulatorarm64-0.12.0-PREVIEW-sources.jar",
          "size": 206085,
          "sha512": "5ae6511bc4c540da998d6a01299735243042bf3f41651ee67d53781bd297129cd9df0dcd21fd92676b103481e50bfcb9a3b83311c5b63c7dd83acf3b53b25ebe",
          "sha256": "7fabf8f94a273e08a955cf6cb0110b98e62b31a4035133fc3d20353bec7550df",
          "sha1": "7c499854b312d6f9376c3a0ffcaf0620998c59d3",
          "md5": "e62eb50eda845b4cb8821fd02230ce97"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iossimulatorarm64-0.12.0-PREVIEW-metadata.jar",
          "url": "supreme-iossimulatorarm64-0.12.0-PREVIEW-metadata.jar",
          "size": 41320,
          "sha512": "4013ccfb8013c75091f801b961717bcb436bc994fb413c8607a11c6e1563475b50f5e0809beff51d5e649e366261cea35650cf34b7f5c7a2ac030747571a9030",
          "sha256": "e1413b2133ec176ada0e7419de5b46de74bbb88f01214627b4a45cb03bcefa06",
          "sha1": "f008fb22e08b230e2c9fc5389a7e9d19490fe4d3",
          "md5": "1536970c73c3ad500189fb23fa8c1144"
        }
      ]
    }
  ]
}
