{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-shared/0.7.1-K2.3.0-SNAPSHOT/testBalloon-framework-shared-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-shared",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-shared-tvosX64Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-shared-tvosx64-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 14969,
          "sha512": "be0797fdb67fdeb306961d1a0d34de5f7cf2081beec90ed53e1e76293befaf05300bebb6eb07c0e1ede9990c313aaf199ff4f665eafa660f148e42a26d8348da",
          "sha256": "2397e3dd000d75cff6952f57097e25113a74e711ff5adb1fe3d3f8c08803efde",
          "sha1": "f24101f7d814410a0879cb75958701d6e5955196",
          "md5": "0ebcaeb84d2be2295ec91a40e7e340d3"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-shared-tvosx64-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-shared-tvosx64-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 5061,
          "sha512": "bd231c91f5cafcb1f505aaa9b9da0db6ec3ded8accd454f795ff1d71fe2c7fac583921062c2841c18fd0f01a358bbf46b9060083dc1e355d23f5b5f6124872a4",
          "sha256": "deb7b7164f14a5a4425ed23c1d06d71a594f482bd25b5b85509e07c544752d96",
          "sha1": "ff21130a6fdf0f8e1b6688e11dbcb1c3cb7b74ab",
          "md5": "32d4af8b2f9d3d76a2ef98211ce1cf89"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-shared-tvosx64-0.7.1-K2.3.0-SNAPSHOT-metadata.jar",
          "url": "testBalloon-framework-shared-tvosx64-0.7.1-K2.3.0-SNAPSHOT-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
