{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable/3.20.0-PREVIEW/indispensable-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "size": 527931,
          "sha512": "a6e23c898c7a43d5f81ded22992a0288ca373655559662e6bc22f058966409858674a48a14987164227bcae98654e79616e312ec615332b7cd5282bbf3255110",
          "sha256": "384048cfdcd39b38c3ebb32cd374523ce7762b66a889755ec683ef65188e209d",
          "sha1": "b1609063e07bdf859a80480e7e1c05b1f90c9352",
          "md5": "550a61803d259ea4ec07a67241a59865"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "size": 527931,
          "sha512": "a6e23c898c7a43d5f81ded22992a0288ca373655559662e6bc22f058966409858674a48a14987164227bcae98654e79616e312ec615332b7cd5282bbf3255110",
          "sha256": "384048cfdcd39b38c3ebb32cd374523ce7762b66a889755ec683ef65188e209d",
          "sha1": "b1609063e07bdf859a80480e7e1c05b1f90c9352",
          "md5": "550a61803d259ea4ec07a67241a59865"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "indispensable-wasm-js-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-wasm-js-3.20.0-PREVIEW-sources.jar",
          "size": 107467,
          "sha512": "aa0f3b0d5618417f5e786715971f6489a6005c7103d6308804094f881017708f7e2ac1957138bf46b2e6cddf2d07f5198dad4775228d61d3f70e69b19046fe0b",
          "sha256": "97b0cd48c5a4734e9d1f334648bdd4dc7b54fbacdc7c3d0dbaaa357656db34d6",
          "sha1": "b275f440776c4545d0f449aa70eb3af2649e958a",
          "md5": "79c9f270c703be3557e1fef2bd63e288"
        }
      ]
    }
  ]
}
