{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable/3.20.0-PREVIEW/indispensable-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "Signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "size": 527932,
          "sha512": "6089ec3820f8831197a7b5cd3120ed871d680150624fef4293b3dd8475bb936b2fe2b669e30cfdfe192b3487f74cb6c4f73dbec4ac1c11d4e854395bd6cd8df5",
          "sha256": "1338140f12b41cbb5c2cabcb01a46d34adaad39b12ac49e22ef9d4d440e583a4",
          "sha1": "0f0f3ce13eb095f0cf6dbe3b53143feea1db8d20",
          "md5": "93de24edb23ac4b739f2a437a44a7ee1"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "Signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "url": "indispensable-wasm-js-3.20.0-PREVIEW.klib",
          "size": 527932,
          "sha512": "6089ec3820f8831197a7b5cd3120ed871d680150624fef4293b3dd8475bb936b2fe2b669e30cfdfe192b3487f74cb6c4f73dbec4ac1c11d4e854395bd6cd8df5",
          "sha256": "1338140f12b41cbb5c2cabcb01a46d34adaad39b12ac49e22ef9d4d440e583a4",
          "sha1": "0f0f3ce13eb095f0cf6dbe3b53143feea1db8d20",
          "md5": "93de24edb23ac4b739f2a437a44a7ee1"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "indispensable-wasm-js-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-wasm-js-3.20.0-PREVIEW-sources.jar",
          "size": 107467,
          "sha512": "aa0f3b0d5618417f5e786715971f6489a6005c7103d6308804094f881017708f7e2ac1957138bf46b2e6cddf2d07f5198dad4775228d61d3f70e69b19046fe0b",
          "sha256": "97b0cd48c5a4734e9d1f334648bdd4dc7b54fbacdc7c3d0dbaaa357656db34d6",
          "sha1": "b275f440776c4545d0f449aa70eb3af2649e958a",
          "md5": "79c9f270c703be3557e1fef2bd63e288"
        }
      ]
    }
  ]
}
