{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-asn1/3.20.0-PREVIEW/indispensable-asn1-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable-asn1",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "kmmresult",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-asn1-jvm-3.20.0-PREVIEW.jar",
          "url": "indispensable-asn1-jvm-3.20.0-PREVIEW.jar",
          "size": 298795,
          "sha512": "de7d7e5d964c5ee329cf63f60a31e97d83316434146986ed301b0fcadab8ec496a89801c18b998ebc891abf2800d056fc4d91fac27bb3603fae448b9dbef8de5",
          "sha256": "7a6ac70c91839ea1eb0440a9d68490faabcb9132b9fd50c6ee1854f92743f553",
          "sha1": "2840ab83530ee37fd1a7e9c754076e6cfdce774b",
          "md5": "19478c8075ed58e9b7d9a21f9f0a958a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "kmmresult",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-asn1-jvm-3.20.0-PREVIEW.jar",
          "url": "indispensable-asn1-jvm-3.20.0-PREVIEW.jar",
          "size": 298795,
          "sha512": "de7d7e5d964c5ee329cf63f60a31e97d83316434146986ed301b0fcadab8ec496a89801c18b998ebc891abf2800d056fc4d91fac27bb3603fae448b9dbef8de5",
          "sha256": "7a6ac70c91839ea1eb0440a9d68490faabcb9132b9fd50c6ee1854f92743f553",
          "sha1": "2840ab83530ee37fd1a7e9c754076e6cfdce774b",
          "md5": "19478c8075ed58e9b7d9a21f9f0a958a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "indispensable-asn1-jvm-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-asn1-jvm-3.20.0-PREVIEW-sources.jar",
          "size": 52030,
          "sha512": "89135764277b3c5e32aaa87d6072f119259e6093e414147159e11f77c3d951a49eb6eedd9292e4f1691954ef10f67106932444f94f67d65b4565d3fb55ba0d89",
          "sha256": "a76afa6fe4e379ee508d71bb7b981f7d997814b66e8a77d6db60d38879eb343f",
          "sha1": "43ac3568dfa88ca5ee821057ba1fcfdbb9e8223c",
          "md5": "d3d92906cabb0bfc965a44fe85f01019"
        }
      ]
    }
  ]
}
