{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-shared/0.7.1-K2.3.0-SNAPSHOT/testBalloon-framework-shared-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-shared",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-shared-androidNativeArm32Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-shared-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 15000,
          "sha512": "24d6448c61d8f61e983dca8604ea17b0f334e248c8e4e46b99adc0704b2fa3bfcc243a8e0b85fcabd940866e0089b668e2282981d5174239fdcb2a11fabd34ee",
          "sha256": "b2393538bb1d0b4fb2d8cace92e84dbdf68ac45e5545434be86aa96195a6368b",
          "sha1": "9e790c67deb65a866edeb74f786d4230c2ea7ed5",
          "md5": "0e4e185795a33691a45bf1c4a0aec944"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-framework-shared-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-shared-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 5061,
          "sha512": "bd231c91f5cafcb1f505aaa9b9da0db6ec3ded8accd454f795ff1d71fe2c7fac583921062c2841c18fd0f01a358bbf46b9060083dc1e355d23f5b5f6124872a4",
          "sha256": "deb7b7164f14a5a4425ed23c1d06d71a594f482bd25b5b85509e07c544752d96",
          "sha1": "ff21130a6fdf0f8e1b6688e11dbcb1c3cb7b74ab",
          "md5": "32d4af8b2f9d3d76a2ef98211ce1cf89"
        }
      ]
    }
  ]
}
