{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals.aar",
          "url": "internals-android-3.20.0-PREVIEW.aar",
          "size": 8941,
          "sha512": "9b44c4eda89a156eaf4a14bc4de2f0d8de440d639dd6184fdb678624d77b66332b1e45d00c19a6dd87e4af3194014e18af68c39ad56944a4e203e7a377668ed8",
          "sha256": "97963095c45954fa92671bb22989680b1662261147661a07ec584e9e2261caad",
          "sha1": "5a01bac3adbe822caf114059c278bb1755cc2f8e",
          "md5": "ccad65f8c4585ad30029dfc1e678d758"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals.aar",
          "url": "internals-android-3.20.0-PREVIEW.aar",
          "size": 8941,
          "sha512": "9b44c4eda89a156eaf4a14bc4de2f0d8de440d639dd6184fdb678624d77b66332b1e45d00c19a6dd87e4af3194014e18af68c39ad56944a4e203e7a377668ed8",
          "sha256": "97963095c45954fa92671bb22989680b1662261147661a07ec584e9e2261caad",
          "sha1": "5a01bac3adbe822caf114059c278bb1755cc2f8e",
          "md5": "ccad65f8c4585ad30029dfc1e678d758"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "internals-android-3.20.0-PREVIEW-sources.jar",
          "url": "internals-android-3.20.0-PREVIEW-sources.jar",
          "size": 3513,
          "sha512": "d0e3582f37c96d9a69542d25308141df25c945a5efc178fc18dc8d5b12e2fdf1a04f303720e71e58e96a91cddf9c3c918f05b26f2eb5d9d38677d3f81f77be5d",
          "sha256": "0e9a5ca0075ad74ca9c81aed7ce95ef732bf096bc89c2e37326a851fa240bfd8",
          "sha1": "4cdb35e155b1ee1fe4d14e15410d2582a17cf323",
          "md5": "3633efc4e81d656d4854cb4d4675c609"
        }
      ]
    }
  ]
}
