package at.asitplus.signum.indispensable.josef

import at.asitplus.signum.indispensable.josef.io.joseCompliantSerializer
import at.asitplus.testballoon.invoke
import com.nimbusds.jose.EncryptionMethod
import com.nimbusds.jose.JOSEObjectType
import com.nimbusds.jose.JWEAlgorithm
import com.nimbusds.jose.JWEHeader
import com.nimbusds.jose.JWEObject
import com.nimbusds.jose.Payload
import com.nimbusds.jose.crypto.AESDecrypter
import com.nimbusds.jose.crypto.AESEncrypter
import com.nimbusds.jose.util.Base64URL
import de.infix.testBalloon.framework.core.testSuite
import io.kotest.matchers.shouldBe
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey

val JweJvmTest by testSuite {

    "compact JWE generated by Nimbus round-trips through new JWE models" {
        val payload = """{"iss":"https://issuer.example","sub":"alice"}""".encodeToByteArray()
        val secretKey = KeyGenerator.getInstance("AES").apply { init(128) }.generateKey()
        val nimbusJwe = JWEObject(
            JWEHeader.Builder(JWEAlgorithm.A128KW, EncryptionMethod.A128GCM)
                .keyID("kid-1")
                .type(JOSEObjectType("application/example+jwe"))
                .contentType("application/example+json")
                .build(),
            Payload(payload),
        )

        nimbusJwe.encrypt(AESEncrypter(secretKey))

        val compact = JweCompact(nimbusJwe.serialize())

        compact.jweHeader.algorithm shouldBe JweAlgorithm.A128KW
        compact.jweHeader.encryption shouldBe JweEncryption.A128GCM
        compact.jweHeader.keyId shouldBe "kid-1"
        compact.jweHeader.type shouldBe "application/example+jwe"
        compact.jweHeader.contentType shouldBe "application/example+json"
        compact.plainProtectedHeader shouldBe nimbusJwe.header.toBase64URL().decode()
        compact.encryptedKey shouldBe nimbusJwe.encryptedKey.decode()
        compact.initializationVector shouldBe nimbusJwe.iv.decode()
        compact.ciphertext shouldBe nimbusJwe.cipherText.decode()
        compact.authenticationTag shouldBe nimbusJwe.authTag.decode()

        val flattened = joseCompliantSerializer.decodeFromString<JweFlattened>(
            joseCompliantSerializer.encodeToString(JweFlattened.serializer(), compact.toJweFlattened())
        )
        val general = joseCompliantSerializer.decodeFromString<JweGeneral>(
            joseCompliantSerializer.encodeToString(JweGeneral.serializer(), listOf(flattened).toJweGeneral())
        )

        general.recipientElements.size shouldBe 1
        general.toJweFlattened().single() shouldBe flattened

        val reparsedByNimbus = JWEObject.parse(general.toJweFlattened().single().toJweCompact().toString())
        reparsedByNimbus.decrypt(AESDecrypter(secretKey))

        reparsedByNimbus.payload.toBytes() shouldBe payload
    }

    "JWE invoke builders with typed JwtClaims can be decrypted by Nimbus" {
        val jwtBaseClaims = JwtBaseClaims(
            issuer = "https://issuer.example",
            subject = "alice",
            audience = "test-suite",
            jwtId = "jwt-1",
        )
        val secretKey = KeyGenerator.getInstance("AES").apply { init(128) }.generateKey()
        val header = JweHeader(
            algorithm = JweAlgorithm.A128KW,
            encryption = JweEncryption.A128GCM,
            keyId = "kid-invoke",
            type = "application/example+jwe",
            contentType = "JWT",
        )
        val protectedHeader = header.toPart()

        val compact = JweCompact(
            protectedHeader = header,
            payload = jwtBaseClaims,
        ) { protectedHeaderPart, plainPayload ->
            protectedHeaderPart shouldBe protectedHeader
            plainPayload shouldBe jwtBaseClaims
            encryptWithNimbus(protectedHeaderPart, plainPayload, secretKey)
        }

        compact.jweHeader shouldBe header
        compact.decryptWithNimbus(secretKey) shouldBe jwtBaseClaims.toPlaintext()

        val flattened = JweFlattened(
            protectedHeader = protectedHeader,
            payload = jwtBaseClaims,
        ) { protectedHeaderPart, unprotectedHeaderPart, plainPayload ->
            protectedHeaderPart shouldBe protectedHeader
            unprotectedHeaderPart shouldBe null
            plainPayload shouldBe jwtBaseClaims
            encryptWithNimbus(protectedHeaderPart, plainPayload, secretKey)
        }

        flattened.jweHeader shouldBe header
        flattened.toJweCompact().decryptWithNimbus(secretKey) shouldBe jwtBaseClaims.toPlaintext()

        val general = JweGeneral(
            protectedHeader = protectedHeader,
            payload = jwtBaseClaims,
        ) { protectedHeaderPart, unprotectedHeaderPart, plainPayload ->
            protectedHeaderPart shouldBe protectedHeader
            unprotectedHeaderPart shouldBe null
            plainPayload shouldBe jwtBaseClaims
            encryptWithNimbus(protectedHeaderPart, plainPayload, secretKey)
        }

        general.jweHeaders.single() shouldBe header
        general.toJweFlattened().single().toJweCompact().decryptWithNimbus(secretKey) shouldBe jwtBaseClaims.toPlaintext()
    }
}

private fun encryptWithNimbus(
    protectedHeader: JweHeader.Part?,
    payload: JwtBaseClaims,
    secretKey: SecretKey,
): JWE.EncryptionOutput {
    val nimbusJwe = JWEObject(
        requireNotNull(protectedHeader).toNimbusHeader(),
        Payload(payload.toPlaintext()),
    )

    nimbusJwe.encrypt(AESEncrypter(secretKey))

    return nimbusJwe.toEncryptionOutput()
}

private fun JweCompact.decryptWithNimbus(secretKey: SecretKey): ByteArray {
    val nimbusJwe = JWEObject.parse(toString())
    nimbusJwe.decrypt(AESDecrypter(secretKey))

    nimbusJwe.header.toBase64URL().decode() shouldBe plainProtectedHeader
    return nimbusJwe.payload.toBytes()
}

private fun JweHeader.Part.toNimbusHeader(): JWEHeader =
    JWEHeader.parse(Base64URL.encode(JweProtectedHeaderSerializer.encodeToByteArray(this)))

private fun JWEObject.toEncryptionOutput(): JWE.EncryptionOutput = JWE.EncryptionOutput(
    iv = iv.decode(),
    cipherText = cipherText.decode(),
    encryptedKey = encryptedKey.decode(),
    authenticationTag = authTag.decode(),
)

private fun JwtBaseClaims.toPlaintext(): ByteArray =
    joseCompliantSerializer.encodeToString(JwtBaseClaims.serializer(), this).encodeToByteArray()
