package at.asitplus.signum.indispensable.josef

import at.asitplus.signum.indispensable.josef.io.joseCompliantSerializer
import at.asitplus.testballoon.invoke
import com.nimbusds.jose.EncryptionMethod
import com.nimbusds.jose.JOSEObjectType
import com.nimbusds.jose.JWEAlgorithm
import com.nimbusds.jose.JWEHeader
import com.nimbusds.jose.JWEObject
import com.nimbusds.jose.Payload
import com.nimbusds.jose.crypto.AESDecrypter
import com.nimbusds.jose.crypto.AESEncrypter
import de.infix.testBalloon.framework.core.testSuite
import io.kotest.matchers.shouldBe
import javax.crypto.KeyGenerator

val JweJvmTest by testSuite {

    "compact JWE generated by Nimbus round-trips through new JWE models" {
        val payload = """{"iss":"https://issuer.example","sub":"alice"}""".encodeToByteArray()
        val secretKey = KeyGenerator.getInstance("AES").apply { init(128) }.generateKey()
        val nimbusJwe = JWEObject(
            JWEHeader.Builder(JWEAlgorithm.A128KW, EncryptionMethod.A128GCM)
                .keyID("kid-1")
                .type(JOSEObjectType("application/example+jwe"))
                .contentType("application/example+json")
                .build(),
            Payload(payload),
        )

        nimbusJwe.encrypt(AESEncrypter(secretKey))

        val compact = JweCompact(nimbusJwe.serialize())

        compact.jweHeader.algorithm shouldBe JweAlgorithm.A128KW
        compact.jweHeader.encryption shouldBe JweEncryption.A128GCM
        compact.jweHeader.keyId shouldBe "kid-1"
        compact.jweHeader.type shouldBe "application/example+jwe"
        compact.jweHeader.contentType shouldBe "application/example+json"
        compact.plainProtectedHeader shouldBe nimbusJwe.header.toBase64URL().decode()
        compact.encryptedKey shouldBe nimbusJwe.encryptedKey.decode()
        compact.initializationVector shouldBe nimbusJwe.iv.decode()
        compact.ciphertext shouldBe nimbusJwe.cipherText.decode()
        compact.authenticationTag shouldBe nimbusJwe.authTag.decode()

        val flattened = joseCompliantSerializer.decodeFromString<JweFlattened>(
            joseCompliantSerializer.encodeToString(JweFlattened.serializer(), compact.toJweFlattened())
        )
        val general = joseCompliantSerializer.decodeFromString<JweGeneral>(
            joseCompliantSerializer.encodeToString(JweGeneral.serializer(), listOf(flattened).toJweGeneral())
        )

        general.recipientElements.size shouldBe 1
        general.toJweFlattened().single() shouldBe flattened

        val reparsedByNimbus = JWEObject.parse(general.toJweFlattened().single().toJweCompact().toString())
        reparsedByNimbus.decrypt(AESDecrypter(secretKey))

        reparsedByNimbus.payload.toBytes() shouldBe payload
    }
}
