{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-asn1/3.20.0-PREVIEW/indispensable-asn1-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable-asn1",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "kmmresult",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-asn1-linuxX64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-asn1-linuxx64-3.20.0-PREVIEW.klib",
          "size": 256841,
          "sha512": "b088ec90c6db3fd9ed719dd9684309cbc399e873e063781daa535754e6ac51f8cb5e75ea557ff427f8f1a9261b56a2ac1de2dd29fe8feca65d26c54169fdddcd",
          "sha256": "e1b7c483da2a8940e722e9aee9fec8cfa4b6aac013ba1d125bed5151d5dc904e",
          "sha1": "a34899f1bdcabfa39a48de91884c6829b8873d76",
          "md5": "514c0a2ed81d9e7713da866c7dc02566"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-asn1-linuxx64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-asn1-linuxx64-3.20.0-PREVIEW-sources.jar",
          "size": 50714,
          "sha512": "3dadb3dc920c32a66ae46048d89d83bbcd10ac7f84a8eb8e2f5cb3b415a4cb5528e1388f53781f6cde239bb5f9fd2ee969ccb43e1fd1afb187d2f31ca05e54ef",
          "sha256": "3bfbe569e36ffdd2d7915fb01797a9086c495a118738d471b46dacd322096c7d",
          "sha1": "2b168fdccda9b546e6021f55b24042b3acec595c",
          "md5": "9de91c17b38ba11a5991bc2bce43835f"
        }
      ]
    }
  ]
}
