{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.12.0-PREVIEW/supreme-0.12.0-PREVIEW.module",
    "group": "Signum",
    "module": "supreme",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-jvm-0.12.0-PREVIEW.jar",
          "url": "supreme-jvm-0.12.0-PREVIEW.jar",
          "size": 511499,
          "sha512": "6e2ea1713f026d5b23703e142fea737103f0fe5a2d12bf077d9dff732b38eef1b1f8a5986f7c3eb088c3ca824e5185f6160611cb0ed13d6424107531052ace20",
          "sha256": "2203b45521097110e9ce4b889b54db437c429683bccd7a3e50360fbe21fa4d6b",
          "sha1": "100d504aab60f34d109d3864f75567548723b819",
          "md5": "fab00f863ab08bda4a62495b59d26326"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-jvm-0.12.0-PREVIEW.jar",
          "url": "supreme-jvm-0.12.0-PREVIEW.jar",
          "size": 511499,
          "sha512": "6e2ea1713f026d5b23703e142fea737103f0fe5a2d12bf077d9dff732b38eef1b1f8a5986f7c3eb088c3ca824e5185f6160611cb0ed13d6424107531052ace20",
          "sha256": "2203b45521097110e9ce4b889b54db437c429683bccd7a3e50360fbe21fa4d6b",
          "sha1": "100d504aab60f34d109d3864f75567548723b819",
          "md5": "fab00f863ab08bda4a62495b59d26326"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "supreme-jvm-0.12.0-PREVIEW-sources.jar",
          "url": "supreme-jvm-0.12.0-PREVIEW-sources.jar",
          "size": 58839,
          "sha512": "1052719ae49279e9579158fc2c743a7266f61d5c08d384e654e73e03622ee3ee96ecdfd26541ef369603768c9e8dac72f156325d83f9bccc7d7cf0edb1d18bb6",
          "sha256": "3b46fcac54c3525149cfde65a155016e06ed22b058aae0c7c28cd671e6702e64",
          "sha1": "c8b25a6fae39eb0eec78cf45f7678ea11ba08247",
          "md5": "495d7ecab111aadcf78b1c1d195ae5e5"
        }
      ]
    }
  ]
}
