{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable/3.20.0-PREVIEW/indispensable-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.83"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable.aar",
          "url": "indispensable-android-3.20.0-PREVIEW.aar",
          "size": 832457,
          "sha512": "e184193976f529d5a32c7dd2f499be2ee4e1524243697a93d76db8beba84b1ad638ccf804b0a9dfe5acff6aca2d6eee6878cd350e9a063a314b299c0554e1f5f",
          "sha256": "e0faeca0244774316336fa1e69fc23642b4e16003e00faf5b24383aa038f9dc1",
          "sha1": "39d1803609c2fc49c86a8d2146ce1404c34cda43",
          "md5": "d346fb56c0ab0f4a1be63a76afb08816"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-oids",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "cidre",
          "version": {
            "requires": "0.3.1"
          }
        },
        {
          "group": "com.eygraber",
          "module": "uri-kmp",
          "version": {
            "requires": "0.0.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.83"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable.aar",
          "url": "indispensable-android-3.20.0-PREVIEW.aar",
          "size": 832457,
          "sha512": "e184193976f529d5a32c7dd2f499be2ee4e1524243697a93d76db8beba84b1ad638ccf804b0a9dfe5acff6aca2d6eee6878cd350e9a063a314b299c0554e1f5f",
          "sha256": "e0faeca0244774316336fa1e69fc23642b4e16003e00faf5b24383aa038f9dc1",
          "sha1": "39d1803609c2fc49c86a8d2146ce1404c34cda43",
          "md5": "d346fb56c0ab0f4a1be63a76afb08816"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "indispensable-android-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-android-3.20.0-PREVIEW-sources.jar",
          "size": 112740,
          "sha512": "d514b6773775c379a2692966987607aaa0188ef843ff7c820d59e2cc47d4e868b4f8fb7a2975c02472539b9c9caa89e7f4512d70dcfa765181dc00bcd4a75179",
          "sha256": "d0668b72033a6c4575dae89658f73ffe5c99e3f987290a808911d719ab5d43fc",
          "sha1": "1be1243bff718698f0f34d2471c5a047763117d7",
          "md5": "945df5a9b49830f04502acb1b7fafafd"
        }
      ]
    }
  ]
}
