package at.asitplus.signum

sealed class CryptoException(message: String? = null, cause: Throwable? = null) : Throwable(message, cause)
open class CryptoOperationFailed(message: String) : CryptoException(message)
open class UnsupportedCryptoException(message: String? = null, cause: Throwable? = null) : CryptoException(message, cause)

open class CertificateException(message: String? = null, cause: Throwable? = null) : Throwable(message, cause)
class CertificateChainValidatorException(message: String) : CertificateException(message)
sealed class CertificateValidityException(message: String) : CertificateException(message)
class CertificateSerialNumberException(message: String) : CertificateValidityException(message)
class SanNotCriticalWithEmptySubjectException(message: String) : CertificateValidityException(message)
class KeyUsageException(message: String) : CertificateException(message)
class ExtendedKeyUsageException(message: String) : CertificateException(message)
sealed class CertificateTimeValidityException(message: String) : CertificateException(message)
class CertificateNotYetValidException(message: String) : CertificateTimeValidityException(message)
class CertificateExpiredException(message: String) : CertificateTimeValidityException(message)
class InvalidCertificateValidityPeriodException(message: String) : CertificateTimeValidityException(message)
sealed class BasicConstraintsException(message: String) : CertificateException(message)
class MissingBasicConstraintsException(message: String) : BasicConstraintsException(message)
class NonCriticalBasicConstraintsException(message: String) : BasicConstraintsException(message)
class MissingCaFlagException(message: String) : BasicConstraintsException(message)
class PathLenConstraintViolationException(message: String) : BasicConstraintsException(message)

class NameConstraintsException(message: String) : CertificateException(message)
class GeneralNameException(message: String) : CertificateException(message)
class CertificatePolicyException(message: String) : CertificateException(message)
sealed class TrustAnchorException(message: String) : CertificateException(message)
class NoTrustedIssuerFoundException(message: String) : TrustAnchorException(message)
class TrustAnchorKeyMismatchException(message: String) : TrustAnchorException(message)
sealed class KeyIdentifierException(message: String) : CertificateException(message)
class MissingSubjectKeyIdentifierException(message: String) : KeyIdentifierException(message)
class CriticalSubjectKeyIdentifierException(message: String) : KeyIdentifierException(message)
class MissingAuthorityKeyIdentifierException(message: String) : KeyIdentifierException(message)
class CriticalAuthorityKeyIdentifierException(message: String) : KeyIdentifierException(message)
