{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.12.0-PREVIEW/supreme-0.12.0-PREVIEW.module",
    "group": "Signum",
    "module": "supreme",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosArm64Main-0.12.0-PREVIEW.klib",
          "url": "supreme-iosarm64-0.12.0-PREVIEW.klib",
          "size": 461783,
          "sha512": "25e21b5a84d650bf0d2a66349fbc568226581ce6d9c62e5485429a03dee62c81ee70edcd7afcd94410dc5348e7e8ed4f393181fce3a543e67056b89f20cc0e30",
          "sha256": "b290cea62aa8c04c56dfd2c9e0bb4124d11e6e2fab28e727180564d285917612",
          "sha1": "9b633d487c77d03b624643a80f141937395234af",
          "md5": "04b292b3a57cdb0f1425a2c49b0106ee"
        },
        {
          "name": "supreme-iosArm64Cinterop-cinteropMain-0.12.0-PREVIEW.klib",
          "url": "supreme-iosarm64-0.12.0-PREVIEW-cinterop-cinterop.klib",
          "size": 27018,
          "sha512": "d3c14757016942dfcaf33b966fb2d2cdded8ec7dfcbf44198e932dcb1959df8e08e088b18aa91012e2a671e86ba4f88f71d89599dfbaf85fcb9000caf3a6e0aa",
          "sha256": "eb4715006b87d99232059d19ce1882a846a90f96fbb4089260b48e846263fc37",
          "sha1": "d0efe588f62db01ea4355c2639b4c839b630908d",
          "md5": "910e3fa378dc998905fd94fd8f6af2a4"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "supreme-iosarm64-0.12.0-PREVIEW-sources.jar",
          "url": "supreme-iosarm64-0.12.0-PREVIEW-sources.jar",
          "size": 206085,
          "sha512": "5ae6511bc4c540da998d6a01299735243042bf3f41651ee67d53781bd297129cd9df0dcd21fd92676b103481e50bfcb9a3b83311c5b63c7dd83acf3b53b25ebe",
          "sha256": "7fabf8f94a273e08a955cf6cb0110b98e62b31a4035133fc3d20353bec7550df",
          "sha1": "7c499854b312d6f9376c3a0ffcaf0620998c59d3",
          "md5": "e62eb50eda845b4cb8821fd02230ce97"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosarm64-0.12.0-PREVIEW-metadata.jar",
          "url": "supreme-iosarm64-0.12.0-PREVIEW-metadata.jar",
          "size": 41320,
          "sha512": "4013ccfb8013c75091f801b961717bcb436bc994fb413c8607a11c6e1563475b50f5e0809beff51d5e649e366261cea35650cf34b7f5c7a2ac030747571a9030",
          "sha256": "e1413b2133ec176ada0e7419de5b46de74bbb88f01214627b4a45cb03bcefa06",
          "sha1": "f008fb22e08b230e2c9fc5389a7e9d19490fe4d3",
          "md5": "1536970c73c3ad500189fb23fa8c1144"
        }
      ]
    }
  ]
}
