{
  "formatVersion": "1.1",
  "component": {
    "url": "../../supreme/0.20.0-PREVIEW/supreme-0.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "supreme",
    "version": "0.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iosSimulatorArm64Main-0.20.0-PREVIEW.klib",
          "url": "supreme-iossimulatorarm64-0.20.0-PREVIEW.klib",
          "size": 461885,
          "sha512": "720093da0fe82b08ac28f00c3faeb989af211534b486c7f1ed37ae95f5a6c788deeb73652f5c23c3352e3569a6579f254c68089348c77ca11a8118c5718d52f8",
          "sha256": "3b239243df44dded1519751b1bfd3ae26d733f25ad167d72bfdf421f2eff5f93",
          "sha1": "6c93d69213b8833901c08d8117be9fd1cfb4f46e",
          "md5": "443003808688d7072a40885ea966804c"
        },
        {
          "name": "supreme-iosSimulatorArm64Cinterop-cinteropMain-0.20.0-PREVIEW.klib",
          "url": "supreme-iossimulatorarm64-0.20.0-PREVIEW-cinterop-cinterop.klib",
          "size": 42967,
          "sha512": "31718d89634256ba4ba0f5f746209e149daa064dacfb6138f6580ac98e7c2903665fcc3cffeb194de1b0df6c9b7595018f3d3047f2000a64374f675fbb026b1c",
          "sha256": "c940d1721360fbea40015c9bad50ce19f14f6e37948ea1060ff57ee268fef740",
          "sha1": "b6eca010a86ce9fbc8e86d082b2e641f602c5b9b",
          "md5": "006de507b111e03b321b154ffae97a2d"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "supreme-iossimulatorarm64-0.20.0-PREVIEW-sources.jar",
          "url": "supreme-iossimulatorarm64-0.20.0-PREVIEW-sources.jar",
          "size": 206090,
          "sha512": "4492a6cff322e597445e922fcd915982bf2bc3fcb568ad36e5f287229e607c74bd26e691d91c95349066072e21d6789b666781c9636152fd773f8e06f4e87f7d",
          "sha256": "4ec8680e2d75acf2a8789c99cf7685d0f3252974dbf1791f4edbfc6eb603a7b6",
          "sha1": "2affdce2d8a61cb1208f7abc948c988983b176f2",
          "md5": "c300e3956f637a148cf525ecc4ccddff"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "at.asitplus.signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.github.aakira",
          "module": "napier",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.kotlincrypto.random",
          "module": "crypto-rand",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "supreme-iossimulatorarm64-0.20.0-PREVIEW-metadata.jar",
          "url": "supreme-iossimulatorarm64-0.20.0-PREVIEW-metadata.jar",
          "size": 42828,
          "sha512": "9e47c69ee1c17c620fe3bd343f8eebdf1e69ebf7ca410a7b0e1618ded3006a0f402e8f282bca177f7bc53f11b606abe516e5f4f52a1d34a93a383e16e306724e",
          "sha256": "273f1d9d5fc33b3d749a55db69db83320afff107e33efdfae130336a526019b6",
          "sha1": "38e2ea335df0f2590d5e540bb291a73317539239",
          "md5": "27c3a8e30ab4f7ca94374670333a1299"
        }
      ]
    }
  ]
}
