{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-framework-shared/0.7.1-K2.3.0-SNAPSHOT/testBalloon-framework-shared-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-framework-shared",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-shared-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-shared-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 13709,
          "sha512": "50b3e70b078bb58976dbec1d376055cbf7a37eac46b2ec63e0adac52034e23e2cbbb47f138d8418ecc92ca47c44b880d000a9fe69483f91c92f4c916592ecf13",
          "sha256": "f99ffc398498ae20693d31e3399f2b6962e9e61f070917b81e4993f9a6c0e58d",
          "sha1": "a0eef0036aac846a1386815e9bd7163fef2b39ec",
          "md5": "7b7623d2b7934e9da8461cb37dcae167"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-framework-shared-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-framework-shared-wasm-js-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 13709,
          "sha512": "50b3e70b078bb58976dbec1d376055cbf7a37eac46b2ec63e0adac52034e23e2cbbb47f138d8418ecc92ca47c44b880d000a9fe69483f91c92f4c916592ecf13",
          "sha256": "f99ffc398498ae20693d31e3399f2b6962e9e61f070917b81e4993f9a6c0e58d",
          "sha1": "a0eef0036aac846a1386815e9bd7163fef2b39ec",
          "md5": "7b7623d2b7934e9da8461cb37dcae167"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "testBalloon-framework-shared-wasm-js-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-framework-shared-wasm-js-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 5061,
          "sha512": "bd231c91f5cafcb1f505aaa9b9da0db6ec3ded8accd454f795ff1d71fe2c7fac583921062c2841c18fd0f01a358bbf46b9060083dc1e355d23f5b5f6124872a4",
          "sha256": "deb7b7164f14a5a4425ed23c1d06d71a594f482bd25b5b85509e07c544752d96",
          "sha1": "ff21130a6fdf0f8e1b6688e11dbcb1c3cb7b74ab",
          "md5": "32d4af8b2f9d3d76a2ef98211ce1cf89"
        }
      ]
    }
  ]
}
