{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-kotest-assertions/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-kotest-assertions-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-kotest-assertions",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "io.kotest",
          "module": "kotest-assertions-core",
          "version": {
            "requires": "5.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-androidNativeArm32Main-0.7.1-K2.3.0-SNAPSHOT.klib",
          "url": "testBalloon-integration-kotest-assertions-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT.klib",
          "size": 4299,
          "sha512": "ead50e78c9ca2e1ddf063bf6c4eeb1fe50ad8c22c4614285a1024daad6a97a928f09004d3eac7f1dac3e4c6368a50053a513c91e790721afd51301539e336ca0",
          "sha256": "c7af53901895aa9567baa35d45df3999681b3a0f77022028597ceac292dad7f1",
          "sha1": "7a644d86b3134aba1457300e7a70f2c502f70dcc",
          "md5": "b8123329a0792215580ecde400c97095"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "testBalloon-integration-kotest-assertions-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-kotest-assertions-androidnativearm32-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 3236,
          "sha512": "898f83a47747cd16f731ae234f7a75243e685d83b3c7732e51b11c1d92dfce285cbaadebcc78adb905a42d2e957c8ac0eb318225e9b7976b216240c895f0032a",
          "sha256": "a888e91399b9e5c57414f5f168fd4fe3e7417eb6a04ccdc1e3183e5d81a57861",
          "sha1": "7db47688e4008a34325218c3ef8aead1631ca286",
          "md5": "d795842e946080d386afd4a6ddb73bf7"
        }
      ]
    }
  ]
}
