{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-blocking-detection-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection.aar",
          "url": "testBalloon-integration-blocking-detection-android-0.7.1-K2.3.0-SNAPSHOT.aar",
          "size": 3027,
          "sha512": "b33623a57f4d9cb64f3fdf4f8dc1f056943baf3adaaed5b79fe0db18df175d983ddea231fc55e6a70b7c02b4c922dfddcfa5e16fdcd0c103a9a26a774b4599b7",
          "sha256": "f4f3163e7771109aa5df010be50e9ab6c0d68f09680d71448d29db00dff04571",
          "sha1": "ca806dc81d8d1eabc5977571d0d4141f6513643f",
          "md5": "eec01a4a6d3e291c8814deddb254ae17"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection.aar",
          "url": "testBalloon-integration-blocking-detection-android-0.7.1-K2.3.0-SNAPSHOT.aar",
          "size": 3027,
          "sha512": "b33623a57f4d9cb64f3fdf4f8dc1f056943baf3adaaed5b79fe0db18df175d983ddea231fc55e6a70b7c02b4c922dfddcfa5e16fdcd0c103a9a26a774b4599b7",
          "sha256": "f4f3163e7771109aa5df010be50e9ab6c0d68f09680d71448d29db00dff04571",
          "sha1": "ca806dc81d8d1eabc5977571d0d4141f6513643f",
          "md5": "eec01a4a6d3e291c8814deddb254ae17"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-android-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-android-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 2978,
          "sha512": "b48e07f093d5516764281420bba656b93ccbad45d30871cbed5f1bb3138a593e09061db7b1591525fc05fa39bacb28f825b82cc691241d4c87c1ce4f00567dd3",
          "sha256": "ada0abfba2b5a3a53372ceb9a5c610664537b3387012ece8d621d3cef4124e4c",
          "sha1": "a3b45767a52d053750f4dd9848fe23ca0f4d1fbe",
          "md5": "8540ddbc4ffa78138fda0f89bf57ac42"
        }
      ]
    }
  ]
}
