{
  "formatVersion": "1.1",
  "component": {
    "group": "Signum",
    "module": "supreme-versionCatalog",
    "version": "0.12.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "supreme-versionCatalog-0.12.0-PREVIEW.toml",
          "url": "supreme-versionCatalog-0.12.0-PREVIEW.toml",
          "size": 2277,
          "sha512": "c3ef81444e5f14397976c6d4febed795081bc1b16a3717caed1d62815e5f65f3cad623a695be48defc59e4a4aab85381b27e10381fe766d40679da95c01a94bf",
          "sha256": "25768313a28467824174ae48ba7383c807c1e1906d08a759857ba453562e417e",
          "sha1": "d7908a6dd1da0cc057cc0a5a23ccb2571912d571",
          "md5": "afadc43622c099b4b421f0fead67d3c0"
        }
      ]
    }
  ]
}
