{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-oids/3.20.0-PREVIEW/indispensable-oids-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "indispensable-oids",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-jvm-3.20.0-PREVIEW.jar",
          "url": "indispensable-oids-jvm-3.20.0-PREVIEW.jar",
          "size": 239697,
          "sha512": "31f46c0db3eeda9757ea2e24d26ab846850880863a68514d7fd43908c515f287a8b7abd4e82ed518bc362bbd36bc42f01ad85a372eee5da12990be52ab262b86",
          "sha256": "443d5d62a48fb9524e5d90f0511ae59f635931141fa621595e6b27b1a1a9160b",
          "sha1": "9330007807af2c9b43a4ca899d99b008bfacbc97",
          "md5": "63a94e1a58f58dd40b3c567d97a3623f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "at.asitplus.signum",
          "module": "indispensable-asn1",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-oids-jvm-3.20.0-PREVIEW.jar",
          "url": "indispensable-oids-jvm-3.20.0-PREVIEW.jar",
          "size": 239697,
          "sha512": "31f46c0db3eeda9757ea2e24d26ab846850880863a68514d7fd43908c515f287a8b7abd4e82ed518bc362bbd36bc42f01ad85a372eee5da12990be52ab262b86",
          "sha256": "443d5d62a48fb9524e5d90f0511ae59f635931141fa621595e6b27b1a1a9160b",
          "sha1": "9330007807af2c9b43a4ca899d99b008bfacbc97",
          "md5": "63a94e1a58f58dd40b3c567d97a3623f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "indispensable-oids-jvm-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-oids-jvm-3.20.0-PREVIEW-sources.jar",
          "size": 87050,
          "sha512": "fc6f1cec4fa7ebc507924ead1b0a626eae184148380f6f0c64f60d234ba1b6532dfb78900478706797fb1cc26205d896dd7d3b290feca56abac0ae5873499ca7",
          "sha256": "e8a4c0b7953f5cb49349bdd5b7cbb26701353f992af01785aba7385d4fc42040",
          "sha1": "b630e3a0a9844af8d0c177f04cbe0519e1fa5039",
          "md5": "c61df4e0a0eff6ba6613137add0bbfb8"
        }
      ]
    }
  ]
}
