{
  "formatVersion": "1.1",
  "component": {
    "url": "../../testBalloon-integration-blocking-detection/0.7.1-K2.3.0-SNAPSHOT/testBalloon-integration-blocking-detection-0.7.1-K2.3.0-SNAPSHOT.module",
    "group": "de.infix.testBalloon",
    "module": "testBalloon-integration-blocking-detection",
    "version": "0.7.1-K2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-jvm-0.7.1-K2.3.0-SNAPSHOT.jar",
          "url": "testBalloon-integration-blocking-detection-jvm-0.7.1-K2.3.0-SNAPSHOT.jar",
          "size": 13233,
          "sha512": "cc2107dd35f16679b84a48444db658263941350c1b0ae5e05643f9bfe15b00171b000d8cabed2645d0211212429bfa53670d5f2fc8ae450386e71c732119ee31",
          "sha256": "a0752ba936e085c68bb4d616b03a28375d261d153bfe71826094e866f904801e",
          "sha1": "43a8f3b106bff6bd4c160365a390d81f7e42e42b",
          "md5": "8b3a15d02750ba031f8aa86e00000d18"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.infix.testBalloon",
          "module": "testBalloon-framework-core",
          "version": {
            "requires": "0.7.1-K2.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0-RC"
          }
        },
        {
          "group": "io.projectreactor.tools",
          "module": "blockhound",
          "version": {
            "requires": "1.0.14.RELEASE"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-debug",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-jvm-0.7.1-K2.3.0-SNAPSHOT.jar",
          "url": "testBalloon-integration-blocking-detection-jvm-0.7.1-K2.3.0-SNAPSHOT.jar",
          "size": 13233,
          "sha512": "cc2107dd35f16679b84a48444db658263941350c1b0ae5e05643f9bfe15b00171b000d8cabed2645d0211212429bfa53670d5f2fc8ae450386e71c732119ee31",
          "sha256": "a0752ba936e085c68bb4d616b03a28375d261d153bfe71826094e866f904801e",
          "sha1": "43a8f3b106bff6bd4c160365a390d81f7e42e42b",
          "md5": "8b3a15d02750ba031f8aa86e00000d18"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "testBalloon-integration-blocking-detection-jvm-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "url": "testBalloon-integration-blocking-detection-jvm-0.7.1-K2.3.0-SNAPSHOT-sources.jar",
          "size": 3733,
          "sha512": "6f1866e4eb7c01dfcf1daf46004d52ca8823d07f40408a0955c542fec3209e87bf0740951cfbd94ecaa557cd3f3f37945bb53849e28a0349eb6817c1036e4507",
          "sha256": "67efcc54e2815ed460a29f7c1b430f65af45f351ef88bd2f114329d8dfbae1e9",
          "sha1": "928558746608a6466d36aa00d324f97cb310f069",
          "md5": "38ed29259be0d431516c3619e36a2fab"
        }
      ]
    }
  ]
}
