{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-androidNativeArm32Main-3.20.0-PREVIEW.klib",
          "url": "internals-androidnativearm32-3.20.0-PREVIEW.klib",
          "size": 12905,
          "sha512": "43f623312c2e22fa4c13341ca371b2d9a66b06c89be9701529ca08deca4347365f7084446b973453973a79a4007b2b92cff5bfd5b9d55f27dbd0771b80acd126",
          "sha256": "1e1ae067530d1d806e51595a89125a53e7ce8cefaca35a08a92b3b6b1a30a1c4",
          "sha1": "d38b350094e717f917ed6ef527ee90e99a53fbaa",
          "md5": "dfb775fe7498f54bf5742bb7d1a8e4f3"
        }
      ]
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "internals-androidnativearm32-3.20.0-PREVIEW-sources.jar",
          "url": "internals-androidnativearm32-3.20.0-PREVIEW-sources.jar",
          "size": 2321,
          "sha512": "4a42b7d015c3f7ff8b44d289de4c34cf382b968bbafb8f9830379813b2605fb8c49e9be34dc199cb836468f32525a142a17278d0e79091a881e8182981fd4fbf",
          "sha256": "2e61ed3e2ef989b03aff245444d1db783169f224aadc1ae0850f783d2413add9",
          "sha1": "6eaa81c269f9dfa36721e11380a28b617a9efaed",
          "md5": "64fcd1d357f4e448fff70042b00c8771"
        }
      ]
    }
  ]
}
