{
  "formatVersion": "1.1",
  "component": {
    "url": "../../internals/3.20.0-PREVIEW/internals-3.20.0-PREVIEW.module",
    "group": "at.asitplus.signum",
    "module": "internals",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-iosArm64Main-3.20.0-PREVIEW.klib",
          "url": "internals-iosarm64-3.20.0-PREVIEW.klib",
          "size": 27579,
          "sha512": "800d657154948b2eb615e87130fd0745220ce7bbd893576c93de885a250fb8e997fb2765ad3e86238eb17d3d3d4fcf864ffb5e965cdcb402e7b1124aefb4dc28",
          "sha256": "63181bf56623235135375c1001ec6d6740a5fa5d311eddb6b1a162f74087cb67",
          "sha1": "0533f007e3162d8cbcd0937c61270890aea8e501",
          "md5": "c7a8603de58bc58fff67488ca3709f8e"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "internals-iosarm64-3.20.0-PREVIEW-sources.jar",
          "url": "internals-iosarm64-3.20.0-PREVIEW-sources.jar",
          "size": 5043,
          "sha512": "0561c3e1afe091eefbc3eb4e151fd416e776d92f346b7af01e8c7eab5a9a005a07caffe9286586f89fa54788c4d4d38888785c60c821a50b84a6dbb506990d17",
          "sha256": "ab9a19c51126900a6fe418c2449a5ef588c2f79148cd42de4feb52f20289ca3a",
          "sha1": "ada914f9b61e62a6c46811abcfcbeebf3a8dcd83",
          "md5": "9fa4b6e5af8c120abff07dd768151111"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "internals-iosarm64-3.20.0-PREVIEW-metadata.jar",
          "url": "internals-iosarm64-3.20.0-PREVIEW-metadata.jar",
          "size": 3911,
          "sha512": "1ee6395381e3a560424055864bc433ceb883e0deabff6fcdcec9b01957344cc8e818a6a1be73fcbfdb3d91f0e38b5667b20db9a391742636e121cf5107dab52a",
          "sha256": "e65a252f779a004d9643b0c89e5f4cf6712fd386c236f5041fc674ba409a9d59",
          "sha1": "11f59658e6c68b50a204cebb5c77726fee45deae",
          "md5": "1cf423e1c70d5e3f80cc9d585fbf4b0d"
        }
      ]
    }
  ]
}
