name: Build iOS Frameworks
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build klibs
        run: ./gradlew iosArm64MainKlibrary iosX64MainKlibrary
      - name: Build XCFrameworks
        run: ./gradlew assembleIndispensableAsn1XCFramework assembleIndispensableXCFramework assembleIndispensableJosefXCFramework assembleIndispensableCosefXCFramework
      - name: Upload debug XCFramework Indispensable
        uses: actions/upload-artifact@v3
        with:
          name: Indispensable-debug.xcframework
          path: |
            indispensable/build/XCFrameworks/debug/
      - name: Upload debug XCFramework IndispensableJosef
        uses: actions/upload-artifact@v3
        with:
          name: IndispensableJosef-debug.xcframework
          path: |
            indispensable-josef/build/XCFrameworks/debug/
      - name: Upload debug XCFramework IndispensableCosef
        uses: actions/upload-artifact@v3
        with:
          name: IndispensableCosef-debug.xcframework
          path: |
            indispensable-cosef/build/XCFrameworks/debug/
      - name: Upload release XCFramework Indispensable
        uses: actions/upload-artifact@v3
        with:
          name: Indispensable-release.xcframework
          path: |
            indispensable/build/XCFrameworks/release/
      - name: Upload release XCFramework IndispensableJosef
        uses: actions/upload-artifact@v3
        with:
          name: IndispensableJosef-release.xcframework
          path: |
            indispensable-josef/build/XCFrameworks/release/
      - name: Upload release XCFramework IndispensableCosef
        uses: actions/upload-artifact@v3
        with:
          name: IndispensableCosef-release.xcframework
          path: |
            indispensable-cosef/build/XCFrameworks/release/
