name: build
on:
  workflow_dispatch:
    inputs:
      kotlin-version:
        description: 'Override Kotlin version?'
        required: false
        default: ''
        type: string
      test-version:
        description: 'Override TestBalloon version (full version string)?'
        required: false
        default: ''
        type: string
jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120
    env:
      KOTLIN_VERSION_ENV: ${{ inputs.kotlin-version }}
      TESTBALLOON_VERSION_OVERRIDE: ${{ inputs.test-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar indispensable-asn1
        uses: actions/upload-artifact@v3
        with:
          name: indispensable-asn1
          path: |
            indispensable-asn1/build/libs/*jar
      - name: Upload jar indispensable
        uses: actions/upload-artifact@v3
        with:
          name: indispensable
          path: |
            indispensable/build/libs/*jar
      - name: Upload jar indispensable-josef
        uses: actions/upload-artifact@v3
        with:
          name: indispensable-josef
          path: |
            indispensable-josef/build/libs/*jar
      - name: Upload jar indispensable-cosef
        uses: actions/upload-artifact@v3
        with:
          name: indispensable-cosef
          path: |
            indispensable-cosef/build/libs/*jar
      - name: Upload jar indispensable-oids
        uses: actions/upload-artifact@v3
        with:
          name: indispensable-oids
          path: |
            indispensable-oids/build/libs/*jar
