name: Guard against use of `KnownOIDs`
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check for `KnownOIDs` usage
        run: |
          RES=$(grep -nr --include="*src/*Main/*.kt" --exclude="*indispensable-*oids/*" "KnownOIDs." || true)
          if [[ -n $RES ]]; then
          # 1 🌶️  Make a visible annotation
          echo "::error title=KnownOIDs%20references%20found::Please remove those references as listed"
          # 2 🪧  Show the offending lines in an expandable group
          echo "::group::References"
          echo "$RES"
          echo "::endgroup::"
          exit 1
          fi
