name: Test iOS implementation
on:
  # still run checks on every PR *before* the merge
  pull_request:

  # run the workflow once more **after** the PR has been merged
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: Checkout (default)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # For pull_request_target, explicitly fetch the PR head
      - name: Checkout PR head (for pull_request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.2.0
      - name: Build klibs
        run: ./gradlew iosArm64MainKlibrary iosSimulatorArm64MainKlibrary
      - name: Run tests
        run: ./gradlew iosSimulatorArm64Test
      - name: 'Add default settings to node calls'
        shell: bash
        run: |
          #
          # The later used dorny/test-reporter@v2 action can throw the following exception when enough tests have been
          # executed:
          #     RangeError: Maximum call stack size exceeded
          #
          # We explicitly increase the max. stack size here to workaround this issue.
          #
          
          which node
          node --version
          
          mv /opt/homebrew/bin/node /opt/homebrew/bin/node_org
          echo '#!/bin/bash' >> /opt/homebrew/bin/node
          echo '/opt/homebrew/bin/node_org --stack-size=4096 $@' >> /opt/homebrew/bin/node
          cat /opt/homebrew/bin/node
          chmod +x /opt/homebrew/bin/node
      - name: Test Report
        uses: dorny/test-reporter@v2
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        if: success() || failure()
        with:
          name: iOS Tests
          path: indispensable/build/test-results/**/TEST*.xml,indispensable-oids/build/test-results/**/TEST*.xml,indispensable-asn1/build/test-results/**/TEST*.xml,indispensable-cosef/build/test-results/**/TEST*.xml,indispensable-josef/build/test-results/**/TEST*.xml,supreme/build/test-results/**/TEST*.xml
          reporter: java-junit
          use-actions-summary: true
