name: Test other Apple implementations
on:
  # still run checks on every PR *before* the merge
  pull_request_target:
    branches:
      - main
      - development

  # run the workflow once more **after** the PR has been merged
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout (default)
        if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # For pull_request_target, explicitly fetch the PR head
      - name: Checkout PR head (for pull_request_target)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.2.0
      - name: Build klibs
        run: ./gradlew iosArm64MainKlibrary iosSimulatorArm64MainKlibrary
      - name: Run tests
        run: ./gradlew tvosX64Test tvosSimulatorArm64Test watchosSimulatorArm64Test watchosX64Test iosX64Test macosArm64Test macosX64Test -x :supreme:linkDebugTestIosX64 -x :supreme:iosX64Test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: iOS Tests
          path: indispensable/build/test-results/**/TEST*.xml,indispensable-oids/build/test-results/**/TEST*.xml,indispensable-asn1/build/test-results/**/TEST*.xml,indispensable-cosef/build/test-results/**/TEST*.xml,indispensable-josef/build/test-results/**/TEST*.xml,supreme/build/test-results/**/TEST*.xml
          reporter: java-junit
