{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-asn1/3.20.0-PREVIEW/indispensable-asn1-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable-asn1",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "at.asitplus",
          "module": "kmmresult",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-asn1-androidNativeX86Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-asn1-androidnativex86-3.20.0-PREVIEW.klib",
          "size": 256853,
          "sha512": "986c4ee5721e0c37cb4125234b9c60fb6070cfbdffbf77739a53651bb21853f847203ec6629eba7500690eb75873e7fec5bf32f59a2348708935082e6a8bca44",
          "sha256": "810d13bfa5b0ba48f9f0a9c3da9d05e2bf0dc9d3c7bedaa5d7521dfaba376552",
          "sha1": "308ac75b31d128557a9085d0dffee27537fd68c8",
          "md5": "717efab79d4d4dbb66f1a9eca79e9881"
        }
      ]
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-asn1-androidnativex86-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-asn1-androidnativex86-3.20.0-PREVIEW-sources.jar",
          "size": 50714,
          "sha512": "3dadb3dc920c32a66ae46048d89d83bbcd10ac7f84a8eb8e2f5cb3b415a4cb5528e1388f53781f6cde239bb5f9fd2ee969ccb43e1fd1afb187d2f31ca05e54ef",
          "sha256": "3bfbe569e36ffdd2d7915fb01797a9086c495a118738d471b46dacd322096c7d",
          "sha1": "2b168fdccda9b546e6021f55b24042b3acec595c",
          "md5": "9de91c17b38ba11a5991bc2bce43835f"
        }
      ]
    }
  ]
}
