{
  "formatVersion": "1.1",
  "component": {
    "url": "../../indispensable-josef/3.20.0-PREVIEW/indispensable-josef-3.20.0-PREVIEW.module",
    "group": "Signum",
    "module": "indispensable-josef",
    "version": "3.20.0-PREVIEW",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "Signum",
          "module": "indispensable",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "at.asitplus",
          "module": "multibase",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "Signum",
          "module": "internals",
          "version": {
            "requires": "3.20.0-PREVIEW"
          }
        },
        {
          "group": "com.ionspin.kotlin",
          "module": "bignum",
          "version": {
            "requires": "0.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "indispensable-josef-androidNativeArm64Main-3.20.0-PREVIEW.klib",
          "url": "indispensable-josef-androidnativearm64-3.20.0-PREVIEW.klib",
          "size": 202439,
          "sha512": "5f8feacf7abeb4d6b676c0eae174b6c2116b7d54b85aaa60c3edbee8244a2687b08d2ff7cd819bb046453a4bfd0d297739dfca9b860c610ecdd8bc01014889e8",
          "sha256": "33057df88f17b4b3da98cf9aeba341ac0cbe125c26dd1b77cd6b57eaf0c54184",
          "sha1": "f17fdf1cc53f40829c8bea2aa60c0053c2d6e76f",
          "md5": "c11ad28f4a7414ef896039ee70682a51"
        }
      ]
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "indispensable-josef-androidnativearm64-3.20.0-PREVIEW-sources.jar",
          "url": "indispensable-josef-androidnativearm64-3.20.0-PREVIEW-sources.jar",
          "size": 34428,
          "sha512": "17bfead8e989cf8f12a249b5d0c0a1fc565ae8488186e84e54b7c3bdcbc0d808802c3f81595e92be734e913c2e3d54c3c797d187fd20eb643609bcacec398624",
          "sha256": "86eb664faeffe738a316ed0aa5f17726e1cd1a4280a3cf31599c319b2f241704",
          "sha1": "fe10a771dd427c76953c4863705a3d7e0cf0cba6",
          "md5": "e2b88bb749c78f522a11df075bc731a5"
        }
      ]
    }
  ]
}
